[package]
name = "http_client"
version = "0.1.0"
edition.workspace = true

[dependencies]
cxx.workspace = true
reqwest.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
serial_test.workspace = true
tempfile.workspace = true
wiremock.workspace = true

[lib]
crate-type = ["staticlib", "rlib"]
