//! C++ FFI surface for the configuration loader.
//!
//! Layout:
//! - **Shared `OptionalT` structs** (`{ is_present: bool, value: T }`) carry
//!   optional scalars across the boundary.
//! - The schema structs (`Config`, `Server`, …) are opaque Rust types whose
//!   getters are auto-generated by `#[derive(ConfigEntries)]`.
//! - Parse entry points return `Result<Box<Config>, ParseError>` — cxx maps
//!   `Err` to a C++ exception (`rust::Error`) via `Display`.

#![allow(unused_imports)] // cxx-bridge resolves these from the parent module.

use crate::error::{ParseError, ParseOutcome};
use crate::schema::Config;
use crate::schema::database::{LedgerTxTables, Sqdb, Sqlite};
use crate::schema::diagnostics::{Insight, Perf};
use crate::schema::grpc::Grpc;
use crate::schema::hashrouter::HashRouter;
use crate::schema::misc::{Crawl, Vl};
use crate::schema::overlay::Overlay;
use crate::schema::reduce_relay::ReduceRelay;
use crate::schema::server::{PortConfig, Server};
use crate::schema::transaction_queue::TransactionQueue;
use crate::schema::voting::Voting;

#[cxx::bridge(namespace = "rs::config")]
mod bridge {
    // ----- Shared optional wrappers -----
    struct OptionalBool {
        is_present: bool,
        value: bool,
    }
    struct OptionalU8 {
        is_present: bool,
        value: u8,
    }
    struct OptionalU16 {
        is_present: bool,
        value: u16,
    }
    struct OptionalU32 {
        is_present: bool,
        value: u32,
    }
    struct OptionalU64 {
        is_present: bool,
        value: u64,
    }
    struct OptionalI32 {
        is_present: bool,
        value: i32,
    }
    struct OptionalString {
        is_present: bool,
        value: String,
    }

    // ----- Opaque schema types + getters -----
    extern "Rust" {
        type Config;
        type Server;
        type PortConfig;
        type Grpc;
        type Overlay;
        type ReduceRelay;
        type TransactionQueue;
        type HashRouter;
        type Sqlite;
        type Sqdb;
        type LedgerTxTables;
        type Insight;
        type Perf;
        type Voting;
        type Crawl;
        type Vl;

        // ----- Parse outcome (std::expected analogue) -----
        type ParseOutcome;

        // ----- Parse entry points -----
        //
        // These always succeed at the FFI boundary — errors are carried inside
        // the returned `ParseOutcome`. The C++ side discriminates via
        // `has_value()` / `has_error()` and then calls `value()` or `error()`.
        fn parse_from_toml_str(s: &str) -> Box<ParseOutcome>;
        fn parse_from_ini_str(s: &str) -> Box<ParseOutcome>;
        fn parse_from_file(path: &str) -> Box<ParseOutcome>;

        // ----- ParseOutcome methods -----
        //
        // `value()` and `error()` use cxx `Result<T>` so that misuse
        // (calling `value()` on an error, or `error()` on a success) throws
        // a C++ exception — same semantics as `std::expected::value()`
        // throwing `bad_expected_access` on `unexpected`.
        fn has_value(self: &ParseOutcome) -> bool;
        fn has_error(self: &ParseOutcome) -> bool;
        fn value(self: &mut ParseOutcome) -> Result<Box<Config>>;
        fn error(self: &ParseOutcome) -> Result<String>;

        // ----- Config: top-level scalars -----
        fn network_quorum(self: &Config) -> OptionalU32;
        fn workers(self: &Config) -> OptionalU32;
        fn io_workers(self: &Config) -> OptionalU32;
        fn prefetch_workers(self: &Config) -> OptionalU32;
        fn max_transactions(self: &Config) -> OptionalU32;
        fn sweep_interval(self: &Config) -> OptionalU32;
        fn peers_max(self: &Config) -> OptionalU32;
        fn peers_in_max(self: &Config) -> OptionalU32;
        fn peers_out_max(self: &Config) -> OptionalU32;
        fn validator_list_threshold(self: &Config) -> OptionalU32;
        fn fee_default(self: &Config) -> OptionalU64;
        fn path_search(self: &Config) -> OptionalI32;
        fn path_search_old(self: &Config) -> OptionalI32;
        fn path_search_fast(self: &Config) -> OptionalI32;
        fn path_search_max(self: &Config) -> OptionalI32;
        fn ssl_verify(self: &Config) -> OptionalBool;
        fn peer_private(self: &Config) -> OptionalBool;
        fn signing_support(self: &Config) -> OptionalBool;
        fn elb_support(self: &Config) -> OptionalBool;
        fn compression(self: &Config) -> OptionalBool;
        fn ledger_replay(self: &Config) -> OptionalBool;
        fn beta_rpc_api(self: &Config) -> OptionalBool;
        fn amendment_majority_time(self: &Config) -> OptionalString;
        fn debug_logfile(self: &Config) -> OptionalString;
        fn node_seed(self: &Config) -> OptionalString;
        fn validation_seed(self: &Config) -> OptionalString;
        fn validator_token(self: &Config) -> OptionalString;
        fn validator_key_revocation(self: &Config) -> OptionalString;
        fn validators_file(self: &Config) -> OptionalString;
        fn server_domain(self: &Config) -> OptionalString;
        fn ssl_verify_file(self: &Config) -> OptionalString;
        fn ssl_verify_dir(self: &Config) -> OptionalString;
        fn database_path(self: &Config) -> OptionalString;

        // ----- Config: list-style top-level keys -----
        fn ips(self: &Config) -> &[String];
        fn ips_fixed(self: &Config) -> &[String];
        fn validators(self: &Config) -> &[String];
        fn validator_keys(self: &Config) -> &[String];
        fn validator_list_sites(self: &Config) -> &[String];
        fn validator_list_keys(self: &Config) -> &[String];
        fn amendments(self: &Config) -> &[String];
        fn veto_amendments(self: &Config) -> &[String];
        fn features(self: &Config) -> &[String];
        fn cluster_nodes(self: &Config) -> &[String];
        fn rpc_startup(self: &Config) -> &[String];

        // ----- Config: nested tables -----
        //
        // Each nested table has a `has_X()` presence check (non-throwing) and
        // an `X()` ref accessor that throws only if called when `has_X()` is
        // false — programmer-error semantics, no try/catch on the happy path.
        //
        // `unsafe fn` is cxx's required acknowledgement that the explicit
        // lifetimes on the ref returns are sound — the references are tied
        // to `&Config`, which C++ holds via `rust::Box<Config>`. No unsafe
        // call on the C++ side.
        fn has_server(self: &Config) -> bool;
        unsafe fn server<'a>(self: &'a Config) -> Result<&'a Server>;
        fn has_grpc(self: &Config) -> bool;
        unsafe fn grpc<'a>(self: &'a Config) -> Result<&'a Grpc>;
        fn has_overlay(self: &Config) -> bool;
        unsafe fn overlay<'a>(self: &'a Config) -> Result<&'a Overlay>;
        fn has_reduce_relay(self: &Config) -> bool;
        unsafe fn reduce_relay<'a>(self: &'a Config) -> Result<&'a ReduceRelay>;
        fn has_transaction_queue(self: &Config) -> bool;
        unsafe fn transaction_queue<'a>(self: &'a Config) -> Result<&'a TransactionQueue>;
        fn has_hashrouter(self: &Config) -> bool;
        unsafe fn hashrouter<'a>(self: &'a Config) -> Result<&'a HashRouter>;
        fn has_sqlite(self: &Config) -> bool;
        unsafe fn sqlite<'a>(self: &'a Config) -> Result<&'a Sqlite>;
        fn has_sqdb(self: &Config) -> bool;
        unsafe fn sqdb<'a>(self: &'a Config) -> Result<&'a Sqdb>;
        fn has_ledger_tx_tables(self: &Config) -> bool;
        unsafe fn ledger_tx_tables<'a>(self: &'a Config) -> Result<&'a LedgerTxTables>;
        fn has_insight(self: &Config) -> bool;
        unsafe fn insight<'a>(self: &'a Config) -> Result<&'a Insight>;
        fn has_perf(self: &Config) -> bool;
        unsafe fn perf<'a>(self: &'a Config) -> Result<&'a Perf>;
        fn has_voting(self: &Config) -> bool;
        unsafe fn voting<'a>(self: &'a Config) -> Result<&'a Voting>;
        fn has_crawl(self: &Config) -> bool;
        unsafe fn crawl<'a>(self: &'a Config) -> Result<&'a Crawl>;
        fn has_vl(self: &Config) -> bool;
        unsafe fn vl<'a>(self: &'a Config) -> Result<&'a Vl>;

        // ----- Server (shared defaults via flatten) -----
        fn defaults(self: &Server) -> &PortConfig;

        // ----- PortConfig getters -----
        fn ip(self: &PortConfig) -> OptionalString;
        fn port(self: &PortConfig) -> OptionalU16;
        fn send_queue_limit(self: &PortConfig) -> OptionalU16;
        fn user(self: &PortConfig) -> OptionalString;
        fn password(self: &PortConfig) -> OptionalString;
        fn admin_user(self: &PortConfig) -> OptionalString;
        fn admin_password(self: &PortConfig) -> OptionalString;
        fn admin(self: &PortConfig) -> &[String];
        fn secure_gateway(self: &PortConfig) -> &[String];
        fn ssl_key(self: &PortConfig) -> OptionalString;
        fn ssl_cert(self: &PortConfig) -> OptionalString;
        fn ssl_chain(self: &PortConfig) -> OptionalString;
        fn ssl_ciphers(self: &PortConfig) -> OptionalString;
        fn permessage_deflate(self: &PortConfig) -> OptionalBool;
        fn client_max_window_bits(self: &PortConfig) -> OptionalU8;
        fn server_max_window_bits(self: &PortConfig) -> OptionalU8;
        fn client_no_context_takeover(self: &PortConfig) -> OptionalBool;
        fn server_no_context_takeover(self: &PortConfig) -> OptionalBool;
        fn compress_level(self: &PortConfig) -> OptionalU8;
        fn memory_level(self: &PortConfig) -> OptionalU8;

        // ----- Grpc -----
        fn ip(self: &Grpc) -> OptionalString;
        fn port(self: &Grpc) -> OptionalU32;
        fn secure_gateway(self: &Grpc) -> &[String];
        fn ssl_cert(self: &Grpc) -> OptionalString;
        fn ssl_key(self: &Grpc) -> OptionalString;
        fn ssl_cert_chain(self: &Grpc) -> OptionalString;
        fn ssl_client_ca(self: &Grpc) -> OptionalString;

        // ----- Overlay -----
        fn public_ip(self: &Overlay) -> OptionalString;
        fn ip_limit(self: &Overlay) -> OptionalI32;
        fn max_unknown_time(self: &Overlay) -> OptionalU32;
        fn max_diverged_time(self: &Overlay) -> OptionalU32;

        // ----- ReduceRelay -----
        fn vp_base_squelch_enable(self: &ReduceRelay) -> OptionalBool;
        fn vp_enable(self: &ReduceRelay) -> OptionalBool;
        fn vp_base_squelch_max_selected_peers(self: &ReduceRelay) -> OptionalU32;
        fn tx_enable(self: &ReduceRelay) -> OptionalBool;
        fn tx_metrics(self: &ReduceRelay) -> OptionalBool;
        fn tx_min_peers(self: &ReduceRelay) -> OptionalU32;
        fn tx_relay_percentage(self: &ReduceRelay) -> OptionalU32;

        // ----- TransactionQueue -----
        fn ledgers_in_queue(self: &TransactionQueue) -> OptionalU32;
        fn minimum_queue_size(self: &TransactionQueue) -> OptionalU32;
        fn retry_sequence_percent(self: &TransactionQueue) -> OptionalU32;
        fn minimum_escalation_multiplier(self: &TransactionQueue) -> OptionalU32;
        fn minimum_txn_in_ledger(self: &TransactionQueue) -> OptionalU32;
        fn minimum_txn_in_ledger_standalone(self: &TransactionQueue) -> OptionalU32;
        fn target_txn_in_ledger(self: &TransactionQueue) -> OptionalU32;
        fn maximum_txn_in_ledger(self: &TransactionQueue) -> OptionalU32;
        fn normal_consensus_increase_percent(self: &TransactionQueue) -> OptionalU32;
        fn slow_consensus_decrease_percent(self: &TransactionQueue) -> OptionalU32;
        fn maximum_txn_per_account(self: &TransactionQueue) -> OptionalU32;
        fn minimum_last_ledger_buffer(self: &TransactionQueue) -> OptionalU32;
        fn zero_basefee_transaction_feelevel(self: &TransactionQueue) -> OptionalU64;

        // ----- HashRouter -----
        fn hold_time(self: &HashRouter) -> OptionalI32;
        fn relay_time(self: &HashRouter) -> OptionalI32;

        // ----- Sqlite -----
        fn page_size(self: &Sqlite) -> OptionalU32;
        fn journal_size_limit(self: &Sqlite) -> OptionalU64;

        // ----- Sqdb (backend variant is skipped — phase 2) -----

        // ----- LedgerTxTables -----
        fn use_tx_tables(self: &LedgerTxTables) -> OptionalBool;

        // ----- Insight -----
        fn address(self: &Insight) -> OptionalString;
        fn prefix(self: &Insight) -> OptionalString;

        // ----- Perf -----
        fn perf_log(self: &Perf) -> OptionalString;
        fn log_interval(self: &Perf) -> OptionalU64;

        // ----- Voting -----
        fn reference_fee(self: &Voting) -> OptionalU64;
        fn account_reserve(self: &Voting) -> OptionalU32;
        fn owner_reserve(self: &Voting) -> OptionalU32;

        // ----- Crawl -----
        fn enabled(self: &Crawl) -> OptionalBool;
        fn overlay(self: &Crawl) -> OptionalBool;
        fn server(self: &Crawl) -> OptionalBool;
        fn counts(self: &Crawl) -> OptionalBool;
        fn unl(self: &Crawl) -> OptionalBool;

        // ----- Vl -----
        fn enabled(self: &Vl) -> OptionalBool;
    }
}

pub use bridge::*;

// ---- Bridge thunk implementations ----
//
// cxx routes the bridge's `parse_*` declarations to free functions defined
// here. The actual logic lives in `crate::parse_from_toml_str` etc.; these
// thunks adapt the signatures (cxx wants bare `&str` paths and a `Box<...>`
// return for opaque types) and lift the parser `Result` into a `ParseOutcome`.

fn parse_from_toml_str(s: &str) -> Box<ParseOutcome> {
    ParseOutcome::from_result(crate::parse_from_toml_str(s))
}

fn parse_from_ini_str(s: &str) -> Box<ParseOutcome> {
    ParseOutcome::from_result(crate::parse_from_ini_str(s))
}

fn parse_from_file(path: &str) -> Box<ParseOutcome> {
    ParseOutcome::from_result(crate::parse_from_file(path))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ok_outcome(s: &str) -> Box<Config> {
        let mut outcome = super::parse_from_toml_str(s);
        assert!(outcome.has_value(), "parse failed: {}", outcome.error().unwrap_or_default());
        outcome.value().expect("has_value=true")
    }

    #[test]
    fn parse_outcome_carries_value() {
        let outcome = super::parse_from_toml_str("network_quorum = 3");
        assert!(outcome.has_value());
        assert!(!outcome.has_error());
    }

    #[test]
    fn parse_outcome_carries_error() {
        let outcome = super::parse_from_toml_str("not_a_real_key = 1");
        assert!(!outcome.has_value());
        assert!(outcome.has_error());
        let msg = outcome.error().expect("has_error=true");
        assert!(msg.contains("not_a_real_key"), "{msg}");
    }

    #[test]
    fn parse_outcome_value_throws_on_error_arm() {
        let mut outcome = super::parse_from_toml_str("not_a_real_key = 1");
        assert!(outcome.value().is_err());
    }

    #[test]
    fn parse_outcome_error_throws_on_value_arm() {
        let outcome = super::parse_from_toml_str("network_quorum = 3");
        assert!(outcome.error().is_err());
    }

    #[test]
    fn parse_outcome_value_consumed_once() {
        let mut outcome = super::parse_from_toml_str("network_quorum = 3");
        assert!(outcome.value().is_ok());
        // Second call must throw — the slot was consumed.
        assert!(outcome.value().is_err());
    }

    #[test]
    fn scalar_getter_present() {
        let cfg = ok_outcome("network_quorum = 3");
        let q = cfg.network_quorum();
        assert!(q.is_present);
        assert_eq!(q.value, 3);
    }

    #[test]
    fn scalar_getter_absent() {
        let cfg = ok_outcome("");
        let q = cfg.network_quorum();
        assert!(!q.is_present);
        assert_eq!(q.value, 0);
    }

    #[test]
    fn string_getter_handles_pathbuf() {
        let cfg = ok_outcome(r#"debug_logfile = "/var/log/xrpld.log""#);
        let p = cfg.debug_logfile();
        assert!(p.is_present);
        assert_eq!(p.value, "/var/log/xrpld.log");
    }

    #[test]
    fn vec_string_getter_returns_slice() {
        let cfg = ok_outcome(r#"ips = ["r.ripple.com 51235", "s2.ripple.com 51235"]"#);
        assert_eq!(cfg.ips(), &["r.ripple.com 51235", "s2.ripple.com 51235"]);
    }

    #[test]
    fn has_x_companion_reports_presence() {
        let cfg = ok_outcome(
            r#"
                [overlay]
                ip_limit = 50
            "#,
        );
        assert!(cfg.has_overlay());
        assert!(!cfg.has_grpc());
    }

    #[test]
    fn nested_getter_ok_when_present() {
        let cfg = ok_outcome(
            r#"
                [overlay]
                ip_limit = 50
            "#,
        );
        let overlay = cfg.overlay().expect("overlay set");
        assert_eq!(overlay.ip_limit().value, 50);
    }

    #[test]
    fn nested_getter_err_when_absent() {
        let cfg = ok_outcome("");
        let err = cfg.overlay().unwrap_err();
        assert!(err.contains("overlay"), "{err}");
    }

    #[test]
    fn server_defaults_flatten_visible_via_getter() {
        let cfg = ok_outcome(
            r#"
                [server]
                send_queue_limit = 500

                [server.ports.port_peer]
                ip = "0.0.0.0"
                port = 51235
            "#,
        );
        let srv = cfg.server().expect("server set");
        let defaults = srv.defaults();
        assert_eq!(defaults.send_queue_limit().value, 500);
        assert!(defaults.send_queue_limit().is_present);
    }

    #[test]
    fn option_vec_string_returns_empty_slice_when_absent() {
        // PortConfig::admin is Option<Vec<String>>; the derive flattens to &[String]
        // returning the empty slice on None.
        let cfg = ok_outcome(
            r#"
                [server]
                send_queue_limit = 500
            "#,
        );
        let srv = cfg.server().unwrap();
        assert!(srv.defaults().admin().is_empty());
    }
}
