//! C++ FFI surface for the configuration loader.
//!
//! Layout:
//! - **Opaque `OptionalT` wrappers** carry optional scalars across the
//!   boundary. Each wraps a native Rust `Option<T>` and exposes `has_value()`,
//!   `value()` (throws if absent), and `value_or(fallback)` to C++. Uniform
//!   API across primitive scalars and `String`.
//! - The schema structs (`Config`, `Server`, …) are opaque Rust types whose
//!   getters are auto-generated by `#[derive(ConfigEntries)]`.
//! - Parse entry points return `Box<ParseOutcome>` — `std::expected`-shaped
//!   wrapper with `has_value() / has_error() / value() / error()`.

#![allow(unused_imports)] // cxx-bridge resolves these from the parent module.

use crate::error::{ParseError, ParseOutcome};
use crate::schema::Config;
use crate::schema::database::{LedgerTxTables, Sqdb, Sqlite};
use crate::schema::diagnostics::{Insight, Perf};
use crate::schema::grpc::Grpc;
use crate::schema::hashrouter::HashRouter;
use crate::schema::misc::{Crawl, Vl};
use crate::schema::overlay::Overlay;
use crate::schema::reduce_relay::ReduceRelay;
use crate::schema::server::{PortConfig, Server};
use crate::schema::transaction_queue::TransactionQueue;
use crate::schema::voting::Voting;

// ---- Opaque optional wrappers ----
//
// Each `OptionalT` wraps a native `Option<T>` and exposes a uniform method
// API to C++ via the cxx bridge. `value()` returns `Result<T>` so misuse
// (calling it on an empty wrapper) throws on the C++ side — same semantics
// as `std::optional::value()` throwing `bad_optional_access`.

macro_rules! optional_type {
    ($name:ident, $inner:ty) => {
        pub struct $name(Option<$inner>);

        impl From<Option<$inner>> for $name {
            fn from(v: Option<$inner>) -> Self {
                Self(v)
            }
        }

        impl $name {
            pub fn has_value(&self) -> bool {
                self.0.is_some()
            }

            pub fn value(&self) -> ::std::result::Result<$inner, ::std::string::String> {
                self.0
                    .clone()
                    .ok_or_else(|| format!("{} has no value", stringify!($name)))
            }

            pub fn value_or(&self, fallback: $inner) -> $inner {
                self.0.clone().unwrap_or(fallback)
            }
        }
    };
}

optional_type!(OptionalBool, bool);
optional_type!(OptionalU8, u8);
optional_type!(OptionalU16, u16);
optional_type!(OptionalU32, u32);
optional_type!(OptionalU64, u64);
optional_type!(OptionalI32, i32);
optional_type!(OptionalString, String);

#[cxx::bridge(namespace = "rs::config")]
mod bridge {
    extern "Rust" {
        // ----- Opaque optional wrappers -----
        type OptionalBool;
        fn has_value(self: &OptionalBool) -> bool;
        fn value(self: &OptionalBool) -> Result<bool>;
        fn value_or(self: &OptionalBool, fallback: bool) -> bool;

        type OptionalU8;
        fn has_value(self: &OptionalU8) -> bool;
        fn value(self: &OptionalU8) -> Result<u8>;
        fn value_or(self: &OptionalU8, fallback: u8) -> u8;

        type OptionalU16;
        fn has_value(self: &OptionalU16) -> bool;
        fn value(self: &OptionalU16) -> Result<u16>;
        fn value_or(self: &OptionalU16, fallback: u16) -> u16;

        type OptionalU32;
        fn has_value(self: &OptionalU32) -> bool;
        fn value(self: &OptionalU32) -> Result<u32>;
        fn value_or(self: &OptionalU32, fallback: u32) -> u32;

        type OptionalU64;
        fn has_value(self: &OptionalU64) -> bool;
        fn value(self: &OptionalU64) -> Result<u64>;
        fn value_or(self: &OptionalU64, fallback: u64) -> u64;

        type OptionalI32;
        fn has_value(self: &OptionalI32) -> bool;
        fn value(self: &OptionalI32) -> Result<i32>;
        fn value_or(self: &OptionalI32, fallback: i32) -> i32;

        type OptionalString;
        fn has_value(self: &OptionalString) -> bool;
        fn value(self: &OptionalString) -> Result<String>;
        fn value_or(self: &OptionalString, fallback: String) -> String;

        // ----- Opaque schema types -----
        type Config;
        type Server;
        type PortConfig;
        type Grpc;
        type Overlay;
        type ReduceRelay;
        type TransactionQueue;
        type HashRouter;
        type Sqlite;
        type Sqdb;
        type LedgerTxTables;
        type Insight;
        type Perf;
        type Voting;
        type Crawl;
        type Vl;

        // ----- Parse outcome (std::expected analogue) -----
        type ParseOutcome;

        // ----- Parse entry points -----
        //
        // These always succeed at the FFI boundary — errors are carried inside
        // the returned `ParseOutcome`. The C++ side discriminates via
        // `has_value()` / `has_error()` and then calls `value()` or `error()`.
        fn parse_from_toml_str(s: &str) -> Box<ParseOutcome>;
        fn parse_from_ini_str(s: &str) -> Box<ParseOutcome>;
        fn parse_from_file(path: &str) -> Box<ParseOutcome>;

        // ----- ParseOutcome methods -----
        //
        // `value()` and `error()` use cxx `Result<T>` so that misuse
        // (calling `value()` on an error, or `error()` on a success) throws
        // a C++ exception — same semantics as `std::expected::value()`
        // throwing `bad_expected_access` on `unexpected`.
        fn has_value(self: &ParseOutcome) -> bool;
        fn has_error(self: &ParseOutcome) -> bool;
        fn value(self: &mut ParseOutcome) -> Result<Box<Config>>;
        fn error(self: &ParseOutcome) -> Result<String>;

        // ----- Config: top-level scalars -----
        fn network_quorum(self: &Config) -> Box<OptionalU32>;
        fn workers(self: &Config) -> Box<OptionalU32>;
        fn io_workers(self: &Config) -> Box<OptionalU32>;
        fn prefetch_workers(self: &Config) -> Box<OptionalU32>;
        fn max_transactions(self: &Config) -> Box<OptionalU32>;
        fn sweep_interval(self: &Config) -> Box<OptionalU32>;
        fn peers_max(self: &Config) -> Box<OptionalU32>;
        fn peers_in_max(self: &Config) -> Box<OptionalU32>;
        fn peers_out_max(self: &Config) -> Box<OptionalU32>;
        fn validator_list_threshold(self: &Config) -> Box<OptionalU32>;
        fn fee_default(self: &Config) -> Box<OptionalU64>;
        fn path_search(self: &Config) -> Box<OptionalI32>;
        fn path_search_old(self: &Config) -> Box<OptionalI32>;
        fn path_search_fast(self: &Config) -> Box<OptionalI32>;
        fn path_search_max(self: &Config) -> Box<OptionalI32>;
        fn ssl_verify(self: &Config) -> Box<OptionalBool>;
        fn peer_private(self: &Config) -> Box<OptionalBool>;
        fn signing_support(self: &Config) -> Box<OptionalBool>;
        fn elb_support(self: &Config) -> Box<OptionalBool>;
        fn compression(self: &Config) -> Box<OptionalBool>;
        fn ledger_replay(self: &Config) -> Box<OptionalBool>;
        fn beta_rpc_api(self: &Config) -> Box<OptionalBool>;
        fn amendment_majority_time(self: &Config) -> Box<OptionalString>;
        fn debug_logfile(self: &Config) -> Box<OptionalString>;
        fn node_seed(self: &Config) -> Box<OptionalString>;
        fn validation_seed(self: &Config) -> Box<OptionalString>;
        fn validator_token(self: &Config) -> Box<OptionalString>;
        fn validator_key_revocation(self: &Config) -> Box<OptionalString>;
        fn validators_file(self: &Config) -> Box<OptionalString>;
        fn server_domain(self: &Config) -> Box<OptionalString>;
        fn ssl_verify_file(self: &Config) -> Box<OptionalString>;
        fn ssl_verify_dir(self: &Config) -> Box<OptionalString>;
        fn database_path(self: &Config) -> Box<OptionalString>;

        // ----- Config: list-style top-level keys -----
        fn ips(self: &Config) -> &[String];
        fn ips_fixed(self: &Config) -> &[String];
        fn validators(self: &Config) -> &[String];
        fn validator_keys(self: &Config) -> &[String];
        fn validator_list_sites(self: &Config) -> &[String];
        fn validator_list_keys(self: &Config) -> &[String];
        fn amendments(self: &Config) -> &[String];
        fn veto_amendments(self: &Config) -> &[String];
        fn features(self: &Config) -> &[String];
        fn cluster_nodes(self: &Config) -> &[String];
        fn rpc_startup(self: &Config) -> &[String];

        // ----- Config: nested tables -----
        //
        // Each nested table has a `has_X()` presence check (non-throwing) and
        // an `X()` ref accessor that throws only if called when `has_X()` is
        // false — programmer-error semantics, no try/catch on the happy path.
        //
        // `unsafe fn` is cxx's required acknowledgement that the explicit
        // lifetimes on the ref returns are sound — the references are tied
        // to `&Config`, which C++ holds via `rust::Box<Config>`. No unsafe
        // call on the C++ side.
        fn has_server(self: &Config) -> bool;
        unsafe fn server<'a>(self: &'a Config) -> Result<&'a Server>;
        fn has_grpc(self: &Config) -> bool;
        unsafe fn grpc<'a>(self: &'a Config) -> Result<&'a Grpc>;
        fn has_overlay(self: &Config) -> bool;
        unsafe fn overlay<'a>(self: &'a Config) -> Result<&'a Overlay>;
        fn has_reduce_relay(self: &Config) -> bool;
        unsafe fn reduce_relay<'a>(self: &'a Config) -> Result<&'a ReduceRelay>;
        fn has_transaction_queue(self: &Config) -> bool;
        unsafe fn transaction_queue<'a>(self: &'a Config) -> Result<&'a TransactionQueue>;
        fn has_hashrouter(self: &Config) -> bool;
        unsafe fn hashrouter<'a>(self: &'a Config) -> Result<&'a HashRouter>;
        fn has_sqlite(self: &Config) -> bool;
        unsafe fn sqlite<'a>(self: &'a Config) -> Result<&'a Sqlite>;
        fn has_sqdb(self: &Config) -> bool;
        unsafe fn sqdb<'a>(self: &'a Config) -> Result<&'a Sqdb>;
        fn has_ledger_tx_tables(self: &Config) -> bool;
        unsafe fn ledger_tx_tables<'a>(self: &'a Config) -> Result<&'a LedgerTxTables>;
        fn has_insight(self: &Config) -> bool;
        unsafe fn insight<'a>(self: &'a Config) -> Result<&'a Insight>;
        fn has_perf(self: &Config) -> bool;
        unsafe fn perf<'a>(self: &'a Config) -> Result<&'a Perf>;
        fn has_voting(self: &Config) -> bool;
        unsafe fn voting<'a>(self: &'a Config) -> Result<&'a Voting>;
        fn has_crawl(self: &Config) -> bool;
        unsafe fn crawl<'a>(self: &'a Config) -> Result<&'a Crawl>;
        fn has_vl(self: &Config) -> bool;
        unsafe fn vl<'a>(self: &'a Config) -> Result<&'a Vl>;

        // ----- Server (shared defaults via flatten) -----
        fn defaults(self: &Server) -> &PortConfig;

        // ----- PortConfig getters -----
        fn ip(self: &PortConfig) -> Box<OptionalString>;
        fn port(self: &PortConfig) -> Box<OptionalU16>;
        fn send_queue_limit(self: &PortConfig) -> Box<OptionalU16>;
        fn user(self: &PortConfig) -> Box<OptionalString>;
        fn password(self: &PortConfig) -> Box<OptionalString>;
        fn admin_user(self: &PortConfig) -> Box<OptionalString>;
        fn admin_password(self: &PortConfig) -> Box<OptionalString>;
        fn admin(self: &PortConfig) -> &[String];
        fn secure_gateway(self: &PortConfig) -> &[String];
        fn ssl_key(self: &PortConfig) -> Box<OptionalString>;
        fn ssl_cert(self: &PortConfig) -> Box<OptionalString>;
        fn ssl_chain(self: &PortConfig) -> Box<OptionalString>;
        fn ssl_ciphers(self: &PortConfig) -> Box<OptionalString>;
        fn permessage_deflate(self: &PortConfig) -> Box<OptionalBool>;
        fn client_max_window_bits(self: &PortConfig) -> Box<OptionalU8>;
        fn server_max_window_bits(self: &PortConfig) -> Box<OptionalU8>;
        fn client_no_context_takeover(self: &PortConfig) -> Box<OptionalBool>;
        fn server_no_context_takeover(self: &PortConfig) -> Box<OptionalBool>;
        fn compress_level(self: &PortConfig) -> Box<OptionalU8>;
        fn memory_level(self: &PortConfig) -> Box<OptionalU8>;

        // ----- Grpc -----
        fn ip(self: &Grpc) -> Box<OptionalString>;
        fn port(self: &Grpc) -> Box<OptionalU32>;
        fn secure_gateway(self: &Grpc) -> &[String];
        fn ssl_cert(self: &Grpc) -> Box<OptionalString>;
        fn ssl_key(self: &Grpc) -> Box<OptionalString>;
        fn ssl_cert_chain(self: &Grpc) -> Box<OptionalString>;
        fn ssl_client_ca(self: &Grpc) -> Box<OptionalString>;

        // ----- Overlay -----
        fn public_ip(self: &Overlay) -> Box<OptionalString>;
        fn ip_limit(self: &Overlay) -> Box<OptionalI32>;
        fn max_unknown_time(self: &Overlay) -> Box<OptionalU32>;
        fn max_diverged_time(self: &Overlay) -> Box<OptionalU32>;

        // ----- ReduceRelay -----
        fn vp_base_squelch_enable(self: &ReduceRelay) -> Box<OptionalBool>;
        fn vp_enable(self: &ReduceRelay) -> Box<OptionalBool>;
        fn vp_base_squelch_max_selected_peers(self: &ReduceRelay) -> Box<OptionalU32>;
        fn tx_enable(self: &ReduceRelay) -> Box<OptionalBool>;
        fn tx_metrics(self: &ReduceRelay) -> Box<OptionalBool>;
        fn tx_min_peers(self: &ReduceRelay) -> Box<OptionalU32>;
        fn tx_relay_percentage(self: &ReduceRelay) -> Box<OptionalU32>;

        // ----- TransactionQueue -----
        fn ledgers_in_queue(self: &TransactionQueue) -> Box<OptionalU32>;
        fn minimum_queue_size(self: &TransactionQueue) -> Box<OptionalU32>;
        fn retry_sequence_percent(self: &TransactionQueue) -> Box<OptionalU32>;
        fn minimum_escalation_multiplier(self: &TransactionQueue) -> Box<OptionalU32>;
        fn minimum_txn_in_ledger(self: &TransactionQueue) -> Box<OptionalU32>;
        fn minimum_txn_in_ledger_standalone(self: &TransactionQueue) -> Box<OptionalU32>;
        fn target_txn_in_ledger(self: &TransactionQueue) -> Box<OptionalU32>;
        fn maximum_txn_in_ledger(self: &TransactionQueue) -> Box<OptionalU32>;
        fn normal_consensus_increase_percent(self: &TransactionQueue) -> Box<OptionalU32>;
        fn slow_consensus_decrease_percent(self: &TransactionQueue) -> Box<OptionalU32>;
        fn maximum_txn_per_account(self: &TransactionQueue) -> Box<OptionalU32>;
        fn minimum_last_ledger_buffer(self: &TransactionQueue) -> Box<OptionalU32>;
        fn zero_basefee_transaction_feelevel(self: &TransactionQueue) -> Box<OptionalU64>;

        // ----- HashRouter -----
        fn hold_time(self: &HashRouter) -> Box<OptionalI32>;
        fn relay_time(self: &HashRouter) -> Box<OptionalI32>;

        // ----- Sqlite -----
        fn page_size(self: &Sqlite) -> Box<OptionalU32>;
        fn journal_size_limit(self: &Sqlite) -> Box<OptionalU64>;

        // ----- Sqdb (backend variant is skipped — phase 2) -----

        // ----- LedgerTxTables -----
        fn use_tx_tables(self: &LedgerTxTables) -> Box<OptionalBool>;

        // ----- Insight -----
        fn address(self: &Insight) -> Box<OptionalString>;
        fn prefix(self: &Insight) -> Box<OptionalString>;

        // ----- Perf -----
        fn perf_log(self: &Perf) -> Box<OptionalString>;
        fn log_interval(self: &Perf) -> Box<OptionalU64>;

        // ----- Voting -----
        fn reference_fee(self: &Voting) -> Box<OptionalU64>;
        fn account_reserve(self: &Voting) -> Box<OptionalU32>;
        fn owner_reserve(self: &Voting) -> Box<OptionalU32>;

        // ----- Crawl -----
        fn enabled(self: &Crawl) -> Box<OptionalBool>;
        fn overlay(self: &Crawl) -> Box<OptionalBool>;
        fn server(self: &Crawl) -> Box<OptionalBool>;
        fn counts(self: &Crawl) -> Box<OptionalBool>;
        fn unl(self: &Crawl) -> Box<OptionalBool>;

        // ----- Vl -----
        fn enabled(self: &Vl) -> Box<OptionalBool>;
    }
}

pub use bridge::*;

// ---- Bridge thunk implementations ----
//
// cxx routes the bridge's `parse_*` declarations to free functions defined
// here. The actual logic lives in `crate::parse_from_toml_str` etc.; these
// thunks adapt the signatures (cxx wants bare `&str` paths and a `Box<...>`
// return for opaque types) and lift the parser `Result` into a `ParseOutcome`.

fn parse_from_toml_str(s: &str) -> Box<ParseOutcome> {
    ParseOutcome::from_result(crate::parse_from_toml_str(s))
}

fn parse_from_ini_str(s: &str) -> Box<ParseOutcome> {
    ParseOutcome::from_result(crate::parse_from_ini_str(s))
}

fn parse_from_file(path: &str) -> Box<ParseOutcome> {
    ParseOutcome::from_result(crate::parse_from_file(path))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ok_outcome(s: &str) -> Box<Config> {
        let mut outcome = super::parse_from_toml_str(s);
        assert!(
            outcome.has_value(),
            "parse failed: {}",
            outcome.error().unwrap_or_default()
        );
        outcome.value().expect("has_value=true")
    }

    #[test]
    fn parse_outcome_carries_value() {
        let outcome = super::parse_from_toml_str("network_quorum = 3");
        assert!(outcome.has_value());
        assert!(!outcome.has_error());
    }

    #[test]
    fn parse_outcome_carries_error() {
        let outcome = super::parse_from_toml_str("not_a_real_key = 1");
        assert!(!outcome.has_value());
        assert!(outcome.has_error());
        let msg = outcome.error().expect("has_error=true");
        assert!(msg.contains("not_a_real_key"), "{msg}");
    }

    #[test]
    fn parse_outcome_value_throws_on_error_arm() {
        let mut outcome = super::parse_from_toml_str("not_a_real_key = 1");
        assert!(outcome.value().is_err());
    }

    #[test]
    fn parse_outcome_error_throws_on_value_arm() {
        let outcome = super::parse_from_toml_str("network_quorum = 3");
        assert!(outcome.error().is_err());
    }

    #[test]
    fn parse_outcome_value_consumed_once() {
        let mut outcome = super::parse_from_toml_str("network_quorum = 3");
        assert!(outcome.value().is_ok());
        assert!(outcome.value().is_err());
    }

    #[test]
    fn scalar_getter_present() {
        let cfg = ok_outcome("network_quorum = 3");
        let q = cfg.network_quorum();
        assert!(q.has_value());
        assert_eq!(q.value().unwrap(), 3);
    }

    #[test]
    fn scalar_getter_absent_throws_on_value() {
        let cfg = ok_outcome("");
        let q = cfg.network_quorum();
        assert!(!q.has_value());
        assert!(q.value().is_err());
    }

    #[test]
    fn scalar_value_or_supplies_fallback() {
        let cfg = ok_outcome("");
        assert_eq!(cfg.network_quorum().value_or(42), 42);
        let cfg = ok_outcome("network_quorum = 7");
        assert_eq!(cfg.network_quorum().value_or(42), 7);
    }

    #[test]
    fn string_getter_handles_pathbuf() {
        let cfg = ok_outcome(r#"debug_logfile = "/var/log/xrpld.log""#);
        let p = cfg.debug_logfile();
        assert!(p.has_value());
        assert_eq!(p.value().unwrap(), "/var/log/xrpld.log");
    }

    #[test]
    fn vec_string_getter_returns_slice() {
        let cfg = ok_outcome(r#"ips = ["r.ripple.com 51235", "s2.ripple.com 51235"]"#);
        assert_eq!(cfg.ips(), &["r.ripple.com 51235", "s2.ripple.com 51235"]);
    }

    #[test]
    fn has_x_companion_reports_presence() {
        let cfg = ok_outcome(
            r#"
                [overlay]
                ip_limit = 50
            "#,
        );
        assert!(cfg.has_overlay());
        assert!(!cfg.has_grpc());
    }

    #[test]
    fn nested_getter_ok_when_present() {
        let cfg = ok_outcome(
            r#"
                [overlay]
                ip_limit = 50
            "#,
        );
        let overlay = cfg.overlay().expect("overlay set");
        assert_eq!(overlay.ip_limit().value().unwrap(), 50);
    }

    #[test]
    fn nested_getter_err_when_absent() {
        let cfg = ok_outcome("");
        let err = cfg.overlay().unwrap_err();
        assert!(err.contains("overlay"), "{err}");
    }

    #[test]
    fn server_defaults_flatten_visible_via_getter() {
        let cfg = ok_outcome(
            r#"
                [server]
                send_queue_limit = 500

                [server.ports.port_peer]
                ip = "0.0.0.0"
                port = 51235
            "#,
        );
        let srv = cfg.server().expect("server set");
        let defaults = srv.defaults();
        assert!(defaults.send_queue_limit().has_value());
        assert_eq!(defaults.send_queue_limit().value().unwrap(), 500);
    }

    #[test]
    fn option_vec_string_returns_empty_slice_when_absent() {
        let cfg = ok_outcome(
            r#"
                [server]
                send_queue_limit = 500
            "#,
        );
        let srv = cfg.server().unwrap();
        assert!(srv.defaults().admin().is_empty());
    }
}
