//! C++ FFI surface for the configuration loader.
//!
//! Layout:
//! - **Opaque `OptionalT` wrappers** carry optional scalars across the
//!   boundary. Each wraps a native Rust `Option<T>` and exposes `has_value()`,
//!   `value()` (throws if absent), and `value_or(fallback)` to C++. Uniform
//!   API across primitive scalars and `String`.
//! - The schema structs (`Config`, `Server`, …) are opaque Rust types whose
//!   getters are auto-generated by `#[derive(ConfigEntries)]`.
//! - Parse entry points return `Box<ParseOutcome>` — `std::expected`-shaped
//!   wrapper with `has_value() / has_error() / value() / error()`.
//!
//! ## Phase-2 additions
//!
//! - **cxx-shared enums** mirror data-less schema enums (`RelayMode`,
//!   `SafetyLevel`, `JournalMode`, `Synchronous`, `TempStore`, `SqdbBackend`,
//!   `InsightServer`, `Protocol`) so both sides see the same variant set.
//!   Conversions go through `From<schema::Foo> for ffi::Foo` helpers.
//! - **`OptionalT` wrappers** follow Pattern A. For polymorphic enums
//!   (`LedgerHistory`, `FetchDepth`, `NetworkId`, `NodeSize`, `PortLimit`) a
//!   `kind()` discriminant plus per-variant accessor(s) is used.
//! - **`OptionalNodeDb`** is the tagged-enum view over `NodeDb` (NuDB |
//!   RocksDB). Variant-specific fields return absent `OptionalU32` when the
//!   wrong variant is active — cleaner than discriminating from C++.
//! - **`Server::ports`** is exposed via `port_names()` / `has_port()` /
//!   `port(name)` (Pattern E).

#![allow(unused_imports)] // cxx-bridge resolves these from the parent module.

use crate::error::{ParseError, ParseOutcome};
use crate::schema::Config;
use crate::schema::database::{
    JournalMode as SchemaJournalMode, LedgerTxTables, NodeDb, SafetyLevel as SchemaSafetyLevel,
    Sqdb, SqdbBackend as SchemaSqdbBackend, Sqlite, Synchronous as SchemaSynchronous,
    TempStore as SchemaTempStore,
};
use crate::schema::diagnostics::{Insight, InsightServer as SchemaInsightServer, Perf};
use crate::schema::enums::{
    FetchDepth as SchemaFetchDepth, FetchDepthName, LedgerHistory as SchemaLedgerHistory,
    LedgerHistoryName, NetworkId as SchemaNetworkId, NetworkIdName, NodeSize as SchemaNodeSize,
    NodeSizeName, RelayMode as SchemaRelayMode,
};
use crate::schema::grpc::Grpc;
use crate::schema::hashrouter::HashRouter;
use crate::schema::misc::{Crawl, Vl};
use crate::schema::overlay::Overlay;
use crate::schema::reduce_relay::ReduceRelay;
use crate::schema::server::{
    PortConfig, PortLimit as SchemaPortLimit, PortLimitName, Protocol as SchemaProtocol, Server,
};
use crate::schema::transaction_queue::TransactionQueue;
use crate::schema::voting::Voting;

// ---- Opaque optional wrappers ----
//
// Each `OptionalT` wraps a native `Option<T>` and exposes a uniform method
// API to C++ via the cxx bridge. `value()` returns `Result<T>` so misuse
// (calling it on an empty wrapper) throws on the C++ side — same semantics
// as `std::optional::value()` throwing `bad_optional_access`.

macro_rules! optional_type {
    ($name:ident, $inner:ty) => {
        pub struct $name(Option<$inner>);

        impl From<Option<$inner>> for $name {
            fn from(v: Option<$inner>) -> Self {
                Self(v)
            }
        }

        impl $name {
            pub fn has_value(&self) -> bool {
                self.0.is_some()
            }

            pub fn value(&self) -> ::std::result::Result<$inner, ::std::string::String> {
                self.0
                    .clone()
                    .ok_or_else(|| format!("{} has no value", stringify!($name)))
            }

            pub fn value_or(&self, fallback: $inner) -> $inner {
                self.0.clone().unwrap_or(fallback)
            }
        }
    };
}

optional_type!(OptionalBool, bool);
optional_type!(OptionalU8, u8);
optional_type!(OptionalU16, u16);
optional_type!(OptionalU32, u32);
optional_type!(OptionalU64, u64);
optional_type!(OptionalI32, i32);
optional_type!(OptionalString, String);

// ---- Phase-2: data-less cxx-shared enum wrappers ----
//
// Each `optional_enum_type!` invocation generates an opaque `OptionalT`
// wrapper around `Option<schema::E>`. `has_value()` is non-throwing;
// `value()` throws when absent and returns the **cxx-shared** ffi enum
// (which is `Copy`) by value. `value_or(fallback: ffi::E) -> ffi::E`
// accepts the fallback in the ffi enum's coordinates so C++ callers can
// pass an enum constant directly.

macro_rules! optional_enum_type {
    ($name:ident, $schema_ty:path, $ffi_ty:ident) => {
        pub struct $name(Option<$schema_ty>);

        impl From<Option<$schema_ty>> for $name {
            fn from(v: Option<$schema_ty>) -> Self {
                Self(v)
            }
        }

        impl $name {
            pub fn has_value(&self) -> bool {
                self.0.is_some()
            }

            pub fn value(&self) -> ::std::result::Result<$ffi_ty, ::std::string::String> {
                self.0
                    .map(Into::into)
                    .ok_or_else(|| format!("{} has no value", stringify!($name)))
            }

            pub fn value_or(&self, fallback: $ffi_ty) -> $ffi_ty {
                self.0.map(Into::into).unwrap_or(fallback)
            }
        }
    };
}

optional_enum_type!(OptionalRelayMode, SchemaRelayMode, RelayMode);
optional_enum_type!(OptionalSafetyLevel, SchemaSafetyLevel, SafetyLevel);
optional_enum_type!(OptionalJournalMode, SchemaJournalMode, JournalMode);
optional_enum_type!(OptionalSynchronous, SchemaSynchronous, Synchronous);
optional_enum_type!(OptionalTempStore, SchemaTempStore, TempStore);
optional_enum_type!(OptionalSqdbBackend, SchemaSqdbBackend, SqdbBackend);
optional_enum_type!(OptionalInsightServer, SchemaInsightServer, InsightServer);

// ---- Phase-2: polymorphic enum wrappers (Pattern D) ----
//
// Polymorphic enums use a `kind()` discriminant plus per-variant accessors.
// `kind()` throws when absent; numeric accessors throw when the wrong
// variant is active OR when absent.

pub struct OptionalLedgerHistory(Option<SchemaLedgerHistory>);

impl From<Option<SchemaLedgerHistory>> for OptionalLedgerHistory {
    fn from(v: Option<SchemaLedgerHistory>) -> Self {
        Self(v)
    }
}

impl OptionalLedgerHistory {
    pub fn has_value(&self) -> bool {
        self.0.is_some()
    }

    pub fn kind(&self) -> Result<LedgerHistoryKind, String> {
        match self.0 {
            Some(SchemaLedgerHistory::Named(LedgerHistoryName::Full)) => {
                Ok(LedgerHistoryKind::Full)
            }
            Some(SchemaLedgerHistory::Named(LedgerHistoryName::None)) => {
                Ok(LedgerHistoryKind::None)
            }
            Some(SchemaLedgerHistory::Numeric(_)) => Ok(LedgerHistoryKind::Numeric),
            None => Err("OptionalLedgerHistory has no value".into()),
        }
    }

    pub fn numeric_value(&self) -> Result<u32, String> {
        match self.0 {
            Some(SchemaLedgerHistory::Numeric(n)) => Ok(n),
            Some(_) => Err("OptionalLedgerHistory is not Numeric".into()),
            None => Err("OptionalLedgerHistory has no value".into()),
        }
    }
}

pub struct OptionalFetchDepth(Option<SchemaFetchDepth>);

impl From<Option<SchemaFetchDepth>> for OptionalFetchDepth {
    fn from(v: Option<SchemaFetchDepth>) -> Self {
        Self(v)
    }
}

impl OptionalFetchDepth {
    pub fn has_value(&self) -> bool {
        self.0.is_some()
    }

    pub fn kind(&self) -> Result<FetchDepthKind, String> {
        match self.0 {
            Some(SchemaFetchDepth::Named(FetchDepthName::Full)) => Ok(FetchDepthKind::Full),
            Some(SchemaFetchDepth::Named(FetchDepthName::None)) => Ok(FetchDepthKind::None),
            Some(SchemaFetchDepth::Numeric(_)) => Ok(FetchDepthKind::Numeric),
            None => Err("OptionalFetchDepth has no value".into()),
        }
    }

    pub fn numeric_value(&self) -> Result<u32, String> {
        match self.0 {
            Some(SchemaFetchDepth::Numeric(n)) => Ok(n),
            Some(_) => Err("OptionalFetchDepth is not Numeric".into()),
            None => Err("OptionalFetchDepth has no value".into()),
        }
    }
}

pub struct OptionalNetworkId(Option<SchemaNetworkId>);

impl From<Option<SchemaNetworkId>> for OptionalNetworkId {
    fn from(v: Option<SchemaNetworkId>) -> Self {
        Self(v)
    }
}

impl OptionalNetworkId {
    pub fn has_value(&self) -> bool {
        self.0.is_some()
    }

    pub fn kind(&self) -> Result<NetworkIdKind, String> {
        match self.0 {
            Some(SchemaNetworkId::Named(NetworkIdName::Main)) => Ok(NetworkIdKind::Main),
            Some(SchemaNetworkId::Named(NetworkIdName::Testnet)) => Ok(NetworkIdKind::Testnet),
            Some(SchemaNetworkId::Named(NetworkIdName::Devnet)) => Ok(NetworkIdKind::Devnet),
            Some(SchemaNetworkId::Numeric(_)) => Ok(NetworkIdKind::Numeric),
            None => Err("OptionalNetworkId has no value".into()),
        }
    }

    pub fn numeric_value(&self) -> Result<u32, String> {
        match self.0 {
            Some(SchemaNetworkId::Numeric(n)) => Ok(n),
            Some(_) => Err("OptionalNetworkId is not Numeric".into()),
            None => Err("OptionalNetworkId has no value".into()),
        }
    }
}

pub struct OptionalNodeSize(Option<SchemaNodeSize>);

impl From<Option<SchemaNodeSize>> for OptionalNodeSize {
    fn from(v: Option<SchemaNodeSize>) -> Self {
        Self(v)
    }
}

impl OptionalNodeSize {
    pub fn has_value(&self) -> bool {
        self.0.is_some()
    }

    pub fn kind(&self) -> Result<NodeSizeKind, String> {
        match self.0 {
            Some(SchemaNodeSize::Named(NodeSizeName::Tiny)) => Ok(NodeSizeKind::Tiny),
            Some(SchemaNodeSize::Named(NodeSizeName::Small)) => Ok(NodeSizeKind::Small),
            Some(SchemaNodeSize::Named(NodeSizeName::Medium)) => Ok(NodeSizeKind::Medium),
            Some(SchemaNodeSize::Named(NodeSizeName::Large)) => Ok(NodeSizeKind::Large),
            Some(SchemaNodeSize::Named(NodeSizeName::Huge)) => Ok(NodeSizeKind::Huge),
            Some(SchemaNodeSize::Numeric(_)) => Ok(NodeSizeKind::Numeric),
            None => Err("OptionalNodeSize has no value".into()),
        }
    }

    pub fn numeric_value(&self) -> Result<u8, String> {
        match self.0 {
            Some(SchemaNodeSize::Numeric(n)) => Ok(n),
            Some(_) => Err("OptionalNodeSize is not Numeric".into()),
            None => Err("OptionalNodeSize has no value".into()),
        }
    }
}

pub struct OptionalPortLimit(Option<SchemaPortLimit>);

impl From<Option<SchemaPortLimit>> for OptionalPortLimit {
    fn from(v: Option<SchemaPortLimit>) -> Self {
        Self(v)
    }
}

impl OptionalPortLimit {
    pub fn has_value(&self) -> bool {
        self.0.is_some()
    }

    pub fn kind(&self) -> Result<PortLimitKind, String> {
        match self.0 {
            Some(SchemaPortLimit::Named(PortLimitName::Unlimited)) => Ok(PortLimitKind::Unlimited),
            Some(SchemaPortLimit::Numeric(_)) => Ok(PortLimitKind::Numeric),
            None => Err("OptionalPortLimit has no value".into()),
        }
    }

    pub fn numeric_value(&self) -> Result<u16, String> {
        match self.0 {
            Some(SchemaPortLimit::Numeric(n)) => Ok(n),
            Some(_) => Err("OptionalPortLimit is not Numeric".into()),
            None => Err("OptionalPortLimit has no value".into()),
        }
    }
}

// ---- Phase-2: tagged NodeDb wrapper ----
//
// `OptionalNodeDb` exposes the flat shape of a `NodeDb` (NuDB | RocksDB):
// every common field is accessible as a uniform `Box<OptionalT>`; variant-
// specific fields (`nudb_block_size`, `cache_mb`, `filter_bits`) return an
// **absent** `OptionalU32` when the wrong variant is active, so C++ callers
// don't have to discriminate via `kind()` for each access.
//
// `path()` is the only required field (no `Option` in the schema) and is
// returned as `Result<String>` — throws when `has_value()` is false.

pub struct OptionalNodeDb(Option<NodeDb>);

impl From<Option<NodeDb>> for OptionalNodeDb {
    fn from(v: Option<NodeDb>) -> Self {
        Self(v)
    }
}

impl OptionalNodeDb {
    pub fn has_value(&self) -> bool {
        self.0.is_some()
    }

    pub fn kind(&self) -> Result<NodeDbKind, String> {
        match &self.0 {
            Some(NodeDb::NuDb(_)) => Ok(NodeDbKind::NuDb),
            Some(NodeDb::RocksDb(_)) => Ok(NodeDbKind::RocksDb),
            None => Err("OptionalNodeDb has no value".into()),
        }
    }

    fn common(&self) -> Option<&crate::schema::database::NodeDbCommon> {
        match &self.0 {
            Some(NodeDb::NuDb(o)) => Some(&o.common),
            Some(NodeDb::RocksDb(o)) => Some(&o.common),
            None => None,
        }
    }

    pub fn path(&self) -> Result<String, String> {
        self.common()
            .map(|c| c.path.to_string_lossy().into_owned())
            .ok_or_else(|| "OptionalNodeDb has no value".into())
    }

    pub fn fast_load(&self) -> Box<OptionalBool> {
        Box::new(OptionalBool(self.common().and_then(|c| c.fast_load)))
    }

    pub fn earliest_seq(&self) -> Box<OptionalU32> {
        Box::new(OptionalU32(self.common().and_then(|c| c.earliest_seq)))
    }

    pub fn online_delete(&self) -> Box<OptionalU32> {
        Box::new(OptionalU32(self.common().and_then(|c| c.online_delete)))
    }

    pub fn advisory_delete(&self) -> Box<OptionalBool> {
        Box::new(OptionalBool(self.common().and_then(|c| c.advisory_delete)))
    }

    pub fn delete_batch(&self) -> Box<OptionalU32> {
        Box::new(OptionalU32(self.common().and_then(|c| c.delete_batch)))
    }

    pub fn back_off_milliseconds(&self) -> Box<OptionalU32> {
        Box::new(OptionalU32(
            self.common().and_then(|c| c.back_off_milliseconds),
        ))
    }

    pub fn age_threshold_seconds(&self) -> Box<OptionalU32> {
        Box::new(OptionalU32(
            self.common().and_then(|c| c.age_threshold_seconds),
        ))
    }

    pub fn recovery_wait_seconds(&self) -> Box<OptionalU32> {
        Box::new(OptionalU32(
            self.common().and_then(|c| c.recovery_wait_seconds),
        ))
    }

    pub fn nudb_block_size(&self) -> Box<OptionalU32> {
        let v = match &self.0 {
            Some(NodeDb::NuDb(o)) => o.nudb_block_size,
            _ => None,
        };
        Box::new(OptionalU32(v))
    }

    pub fn cache_mb(&self) -> Box<OptionalU32> {
        let v = match &self.0 {
            Some(NodeDb::RocksDb(o)) => o.cache_mb,
            _ => None,
        };
        Box::new(OptionalU32(v))
    }

    pub fn filter_bits(&self) -> Box<OptionalU32> {
        let v = match &self.0 {
            Some(NodeDb::RocksDb(o)) => o.filter_bits,
            _ => None,
        };
        Box::new(OptionalU32(v))
    }
}

// ---- Phase-2: hand-written getters on schema types ----
//
// The fields these access are marked `#[config_entry(skip)]` so the derive
// doesn't emit anything. Each getter constructs the corresponding opaque
// wrapper via the bridge's `Box<OptionalT>` interface.

impl Config {
    pub fn relay_proposals(&self) -> Box<OptionalRelayMode> {
        Box::new(self.relay_proposals.into())
    }

    pub fn relay_validations(&self) -> Box<OptionalRelayMode> {
        Box::new(self.relay_validations.into())
    }

    pub fn ledger_history(&self) -> Box<OptionalLedgerHistory> {
        Box::new(self.ledger_history.into())
    }

    pub fn fetch_depth(&self) -> Box<OptionalFetchDepth> {
        Box::new(self.fetch_depth.into())
    }

    pub fn network_id(&self) -> Box<OptionalNetworkId> {
        Box::new(self.network_id.into())
    }

    pub fn node_size(&self) -> Box<OptionalNodeSize> {
        Box::new(self.node_size.into())
    }

    pub fn node_db(&self) -> Box<OptionalNodeDb> {
        Box::new(self.node_db.clone().into())
    }

    pub fn import_db(&self) -> Box<OptionalNodeDb> {
        Box::new(self.import_db.clone().into())
    }
}

impl Sqlite {
    pub fn safety_level(&self) -> Box<OptionalSafetyLevel> {
        Box::new(self.safety_level.into())
    }

    pub fn journal_mode(&self) -> Box<OptionalJournalMode> {
        Box::new(self.journal_mode.into())
    }

    pub fn synchronous(&self) -> Box<OptionalSynchronous> {
        Box::new(self.synchronous.into())
    }

    pub fn temp_store(&self) -> Box<OptionalTempStore> {
        Box::new(self.temp_store.into())
    }
}

impl Sqdb {
    pub fn backend(&self) -> Box<OptionalSqdbBackend> {
        Box::new(self.backend.into())
    }
}

impl Insight {
    pub fn server(&self) -> Box<OptionalInsightServer> {
        Box::new(self.server.into())
    }
}

impl Server {
    /// Names of every per-port section in sorted order (the underlying
    /// container is a `BTreeMap`, so iteration is already sorted).
    pub fn port_names(&self) -> Vec<String> {
        self.ports.keys().cloned().collect()
    }

    pub fn has_port(&self, name: &str) -> bool {
        self.ports.contains_key(name)
    }

    /// Lookup a named port. Throws across FFI when no port with that name
    /// exists — programmer error, same semantics as the rest of the surface.
    pub fn port(&self, name: &str) -> Result<&PortConfig, String> {
        self.ports
            .get(name)
            .ok_or_else(|| format!("config: no server.ports.{name}"))
    }
}

impl PortConfig {
    /// Empty `Vec` when the field is absent — matches the
    /// `Option<Vec<String>>` convention used elsewhere in the bridge for
    /// list-shaped optional fields.
    pub fn protocols(&self) -> Vec<Protocol> {
        match &self.protocol {
            Some(v) => v.iter().copied().map(Into::into).collect(),
            None => Vec::new(),
        }
    }

    pub fn limit(&self) -> Box<OptionalPortLimit> {
        Box::new(self.limit.into())
    }
}

#[cxx::bridge(namespace = "rs::config")]
mod bridge {
    // ----- Shared cxx enums (mirror data-less schema enums) -----
    //
    // Variants are declared in the same order as the schema enums so the
    // `From<schema::E> for ffi::E` impls below can match on shape.

    enum RelayMode {
        All,
        Trusted,
        DropUntrusted,
    }

    enum SafetyLevel {
        High,
        Low,
    }

    enum JournalMode {
        Delete,
        Truncate,
        Persist,
        Memory,
        Wal,
        Off,
    }

    enum Synchronous {
        Off,
        Normal,
        Full,
        Extra,
    }

    enum TempStore {
        Default,
        File,
        Memory,
    }

    enum SqdbBackend {
        Sqlite,
    }

    enum InsightServer {
        Statsd,
    }

    enum Protocol {
        Http,
        Https,
        Ws,
        Wss,
        Peer,
    }

    // ----- Discriminant enums for polymorphic schema types -----

    enum LedgerHistoryKind {
        Full,
        None,
        Numeric,
    }

    enum FetchDepthKind {
        Full,
        None,
        Numeric,
    }

    enum NetworkIdKind {
        Main,
        Testnet,
        Devnet,
        Numeric,
    }

    enum NodeSizeKind {
        Tiny,
        Small,
        Medium,
        Large,
        Huge,
        Numeric,
    }

    enum PortLimitKind {
        Unlimited,
        Numeric,
    }

    enum NodeDbKind {
        NuDb,
        RocksDb,
    }

    extern "Rust" {
        // ----- Opaque optional wrappers -----
        type OptionalBool;
        fn has_value(self: &OptionalBool) -> bool;
        fn value(self: &OptionalBool) -> Result<bool>;
        fn value_or(self: &OptionalBool, fallback: bool) -> bool;

        type OptionalU8;
        fn has_value(self: &OptionalU8) -> bool;
        fn value(self: &OptionalU8) -> Result<u8>;
        fn value_or(self: &OptionalU8, fallback: u8) -> u8;

        type OptionalU16;
        fn has_value(self: &OptionalU16) -> bool;
        fn value(self: &OptionalU16) -> Result<u16>;
        fn value_or(self: &OptionalU16, fallback: u16) -> u16;

        type OptionalU32;
        fn has_value(self: &OptionalU32) -> bool;
        fn value(self: &OptionalU32) -> Result<u32>;
        fn value_or(self: &OptionalU32, fallback: u32) -> u32;

        type OptionalU64;
        fn has_value(self: &OptionalU64) -> bool;
        fn value(self: &OptionalU64) -> Result<u64>;
        fn value_or(self: &OptionalU64, fallback: u64) -> u64;

        type OptionalI32;
        fn has_value(self: &OptionalI32) -> bool;
        fn value(self: &OptionalI32) -> Result<i32>;
        fn value_or(self: &OptionalI32, fallback: i32) -> i32;

        type OptionalString;
        fn has_value(self: &OptionalString) -> bool;
        fn value(self: &OptionalString) -> Result<String>;
        fn value_or(self: &OptionalString, fallback: String) -> String;

        // ----- Phase-2 optional-enum wrappers -----
        type OptionalRelayMode;
        fn has_value(self: &OptionalRelayMode) -> bool;
        fn value(self: &OptionalRelayMode) -> Result<RelayMode>;
        fn value_or(self: &OptionalRelayMode, fallback: RelayMode) -> RelayMode;

        type OptionalSafetyLevel;
        fn has_value(self: &OptionalSafetyLevel) -> bool;
        fn value(self: &OptionalSafetyLevel) -> Result<SafetyLevel>;
        fn value_or(self: &OptionalSafetyLevel, fallback: SafetyLevel) -> SafetyLevel;

        type OptionalJournalMode;
        fn has_value(self: &OptionalJournalMode) -> bool;
        fn value(self: &OptionalJournalMode) -> Result<JournalMode>;
        fn value_or(self: &OptionalJournalMode, fallback: JournalMode) -> JournalMode;

        type OptionalSynchronous;
        fn has_value(self: &OptionalSynchronous) -> bool;
        fn value(self: &OptionalSynchronous) -> Result<Synchronous>;
        fn value_or(self: &OptionalSynchronous, fallback: Synchronous) -> Synchronous;

        type OptionalTempStore;
        fn has_value(self: &OptionalTempStore) -> bool;
        fn value(self: &OptionalTempStore) -> Result<TempStore>;
        fn value_or(self: &OptionalTempStore, fallback: TempStore) -> TempStore;

        type OptionalSqdbBackend;
        fn has_value(self: &OptionalSqdbBackend) -> bool;
        fn value(self: &OptionalSqdbBackend) -> Result<SqdbBackend>;
        fn value_or(self: &OptionalSqdbBackend, fallback: SqdbBackend) -> SqdbBackend;

        type OptionalInsightServer;
        fn has_value(self: &OptionalInsightServer) -> bool;
        fn value(self: &OptionalInsightServer) -> Result<InsightServer>;
        fn value_or(self: &OptionalInsightServer, fallback: InsightServer) -> InsightServer;

        // ----- Phase-2 polymorphic wrappers -----
        type OptionalLedgerHistory;
        fn has_value(self: &OptionalLedgerHistory) -> bool;
        fn kind(self: &OptionalLedgerHistory) -> Result<LedgerHistoryKind>;
        fn numeric_value(self: &OptionalLedgerHistory) -> Result<u32>;

        type OptionalFetchDepth;
        fn has_value(self: &OptionalFetchDepth) -> bool;
        fn kind(self: &OptionalFetchDepth) -> Result<FetchDepthKind>;
        fn numeric_value(self: &OptionalFetchDepth) -> Result<u32>;

        type OptionalNetworkId;
        fn has_value(self: &OptionalNetworkId) -> bool;
        fn kind(self: &OptionalNetworkId) -> Result<NetworkIdKind>;
        fn numeric_value(self: &OptionalNetworkId) -> Result<u32>;

        type OptionalNodeSize;
        fn has_value(self: &OptionalNodeSize) -> bool;
        fn kind(self: &OptionalNodeSize) -> Result<NodeSizeKind>;
        fn numeric_value(self: &OptionalNodeSize) -> Result<u8>;

        type OptionalPortLimit;
        fn has_value(self: &OptionalPortLimit) -> bool;
        fn kind(self: &OptionalPortLimit) -> Result<PortLimitKind>;
        fn numeric_value(self: &OptionalPortLimit) -> Result<u16>;

        // ----- Phase-2 tagged NodeDb wrapper -----
        type OptionalNodeDb;
        fn has_value(self: &OptionalNodeDb) -> bool;
        fn kind(self: &OptionalNodeDb) -> Result<NodeDbKind>;
        fn path(self: &OptionalNodeDb) -> Result<String>;
        fn fast_load(self: &OptionalNodeDb) -> Box<OptionalBool>;
        fn earliest_seq(self: &OptionalNodeDb) -> Box<OptionalU32>;
        fn online_delete(self: &OptionalNodeDb) -> Box<OptionalU32>;
        fn advisory_delete(self: &OptionalNodeDb) -> Box<OptionalBool>;
        fn delete_batch(self: &OptionalNodeDb) -> Box<OptionalU32>;
        fn back_off_milliseconds(self: &OptionalNodeDb) -> Box<OptionalU32>;
        fn age_threshold_seconds(self: &OptionalNodeDb) -> Box<OptionalU32>;
        fn recovery_wait_seconds(self: &OptionalNodeDb) -> Box<OptionalU32>;
        fn nudb_block_size(self: &OptionalNodeDb) -> Box<OptionalU32>;
        fn cache_mb(self: &OptionalNodeDb) -> Box<OptionalU32>;
        fn filter_bits(self: &OptionalNodeDb) -> Box<OptionalU32>;

        // ----- Opaque schema types -----
        type Config;
        type Server;
        type PortConfig;
        type Grpc;
        type Overlay;
        type ReduceRelay;
        type TransactionQueue;
        type HashRouter;
        type Sqlite;
        type Sqdb;
        type LedgerTxTables;
        type Insight;
        type Perf;
        type Voting;
        type Crawl;
        type Vl;

        // ----- Parse outcome (std::expected analogue) -----
        type ParseOutcome;

        // ----- Parse entry points -----
        //
        // These always succeed at the FFI boundary — errors are carried inside
        // the returned `ParseOutcome`. The C++ side discriminates via
        // `has_value()` / `has_error()` and then calls `value()` or `error()`.
        fn parse_from_toml_str(s: &str) -> Box<ParseOutcome>;
        fn parse_from_ini_str(s: &str) -> Box<ParseOutcome>;
        fn parse_from_file(path: &str) -> Box<ParseOutcome>;

        // ----- ParseOutcome methods -----
        //
        // `value()` and `error()` use cxx `Result<T>` so that misuse
        // (calling `value()` on an error, or `error()` on a success) throws
        // a C++ exception — same semantics as `std::expected::value()`
        // throwing `bad_expected_access` on `unexpected`.
        fn has_value(self: &ParseOutcome) -> bool;
        fn has_error(self: &ParseOutcome) -> bool;
        fn value(self: &mut ParseOutcome) -> Result<Box<Config>>;
        fn error(self: &ParseOutcome) -> Result<String>;

        // ----- Config: top-level scalars -----
        fn network_quorum(self: &Config) -> Box<OptionalU32>;
        fn workers(self: &Config) -> Box<OptionalU32>;
        fn io_workers(self: &Config) -> Box<OptionalU32>;
        fn prefetch_workers(self: &Config) -> Box<OptionalU32>;
        fn max_transactions(self: &Config) -> Box<OptionalU32>;
        fn sweep_interval(self: &Config) -> Box<OptionalU32>;
        fn peers_max(self: &Config) -> Box<OptionalU32>;
        fn peers_in_max(self: &Config) -> Box<OptionalU32>;
        fn peers_out_max(self: &Config) -> Box<OptionalU32>;
        fn validator_list_threshold(self: &Config) -> Box<OptionalU32>;
        fn fee_default(self: &Config) -> Box<OptionalU64>;
        fn path_search(self: &Config) -> Box<OptionalI32>;
        fn path_search_old(self: &Config) -> Box<OptionalI32>;
        fn path_search_fast(self: &Config) -> Box<OptionalI32>;
        fn path_search_max(self: &Config) -> Box<OptionalI32>;
        fn ssl_verify(self: &Config) -> Box<OptionalBool>;
        fn peer_private(self: &Config) -> Box<OptionalBool>;
        fn signing_support(self: &Config) -> Box<OptionalBool>;
        fn elb_support(self: &Config) -> Box<OptionalBool>;
        fn compression(self: &Config) -> Box<OptionalBool>;
        fn ledger_replay(self: &Config) -> Box<OptionalBool>;
        fn beta_rpc_api(self: &Config) -> Box<OptionalBool>;
        fn amendment_majority_time(self: &Config) -> Box<OptionalString>;
        fn debug_logfile(self: &Config) -> Box<OptionalString>;
        fn node_seed(self: &Config) -> Box<OptionalString>;
        fn validation_seed(self: &Config) -> Box<OptionalString>;
        fn validator_token(self: &Config) -> Box<OptionalString>;
        fn validator_key_revocation(self: &Config) -> Box<OptionalString>;
        fn validators_file(self: &Config) -> Box<OptionalString>;
        fn server_domain(self: &Config) -> Box<OptionalString>;
        fn ssl_verify_file(self: &Config) -> Box<OptionalString>;
        fn ssl_verify_dir(self: &Config) -> Box<OptionalString>;
        fn database_path(self: &Config) -> Box<OptionalString>;

        // ----- Config: list-style top-level keys -----
        fn ips(self: &Config) -> &[String];
        fn ips_fixed(self: &Config) -> &[String];
        fn validators(self: &Config) -> &[String];
        fn validator_keys(self: &Config) -> &[String];
        fn validator_list_sites(self: &Config) -> &[String];
        fn validator_list_keys(self: &Config) -> &[String];
        fn amendments(self: &Config) -> &[String];
        fn veto_amendments(self: &Config) -> &[String];
        fn features(self: &Config) -> &[String];
        fn cluster_nodes(self: &Config) -> &[String];
        fn rpc_startup(self: &Config) -> &[String];

        // ----- Config: phase-2 hand-written getters -----
        fn relay_proposals(self: &Config) -> Box<OptionalRelayMode>;
        fn relay_validations(self: &Config) -> Box<OptionalRelayMode>;
        fn ledger_history(self: &Config) -> Box<OptionalLedgerHistory>;
        fn fetch_depth(self: &Config) -> Box<OptionalFetchDepth>;
        fn network_id(self: &Config) -> Box<OptionalNetworkId>;
        fn node_size(self: &Config) -> Box<OptionalNodeSize>;
        fn node_db(self: &Config) -> Box<OptionalNodeDb>;
        fn import_db(self: &Config) -> Box<OptionalNodeDb>;

        // ----- Config: nested tables -----
        //
        // Each nested table has a `has_X()` presence check (non-throwing) and
        // an `X()` ref accessor that throws only if called when `has_X()` is
        // false — programmer-error semantics, no try/catch on the happy path.
        //
        // `unsafe fn` is cxx's required acknowledgement that the explicit
        // lifetimes on the ref returns are sound — the references are tied
        // to `&Config`, which C++ holds via `rust::Box<Config>`. No unsafe
        // call on the C++ side.
        fn has_server(self: &Config) -> bool;
        unsafe fn server<'a>(self: &'a Config) -> Result<&'a Server>;
        fn has_grpc(self: &Config) -> bool;
        unsafe fn grpc<'a>(self: &'a Config) -> Result<&'a Grpc>;
        fn has_overlay(self: &Config) -> bool;
        unsafe fn overlay<'a>(self: &'a Config) -> Result<&'a Overlay>;
        fn has_reduce_relay(self: &Config) -> bool;
        unsafe fn reduce_relay<'a>(self: &'a Config) -> Result<&'a ReduceRelay>;
        fn has_transaction_queue(self: &Config) -> bool;
        unsafe fn transaction_queue<'a>(self: &'a Config) -> Result<&'a TransactionQueue>;
        fn has_hashrouter(self: &Config) -> bool;
        unsafe fn hashrouter<'a>(self: &'a Config) -> Result<&'a HashRouter>;
        fn has_sqlite(self: &Config) -> bool;
        unsafe fn sqlite<'a>(self: &'a Config) -> Result<&'a Sqlite>;
        fn has_sqdb(self: &Config) -> bool;
        unsafe fn sqdb<'a>(self: &'a Config) -> Result<&'a Sqdb>;
        fn has_ledger_tx_tables(self: &Config) -> bool;
        unsafe fn ledger_tx_tables<'a>(self: &'a Config) -> Result<&'a LedgerTxTables>;
        fn has_insight(self: &Config) -> bool;
        unsafe fn insight<'a>(self: &'a Config) -> Result<&'a Insight>;
        fn has_perf(self: &Config) -> bool;
        unsafe fn perf<'a>(self: &'a Config) -> Result<&'a Perf>;
        fn has_voting(self: &Config) -> bool;
        unsafe fn voting<'a>(self: &'a Config) -> Result<&'a Voting>;
        fn has_crawl(self: &Config) -> bool;
        unsafe fn crawl<'a>(self: &'a Config) -> Result<&'a Crawl>;
        fn has_vl(self: &Config) -> bool;
        unsafe fn vl<'a>(self: &'a Config) -> Result<&'a Vl>;

        // ----- Server (shared defaults via flatten) -----
        fn defaults(self: &Server) -> &PortConfig;

        // ----- Server::ports map (Pattern E) -----
        fn port_names(self: &Server) -> Vec<String>;
        fn has_port(self: &Server, name: &str) -> bool;
        unsafe fn port<'a>(self: &'a Server, name: &str) -> Result<&'a PortConfig>;

        // ----- PortConfig getters -----
        fn ip(self: &PortConfig) -> Box<OptionalString>;
        fn port(self: &PortConfig) -> Box<OptionalU16>;
        fn send_queue_limit(self: &PortConfig) -> Box<OptionalU16>;
        fn user(self: &PortConfig) -> Box<OptionalString>;
        fn password(self: &PortConfig) -> Box<OptionalString>;
        fn admin_user(self: &PortConfig) -> Box<OptionalString>;
        fn admin_password(self: &PortConfig) -> Box<OptionalString>;
        fn admin(self: &PortConfig) -> &[String];
        fn secure_gateway(self: &PortConfig) -> &[String];
        fn ssl_key(self: &PortConfig) -> Box<OptionalString>;
        fn ssl_cert(self: &PortConfig) -> Box<OptionalString>;
        fn ssl_chain(self: &PortConfig) -> Box<OptionalString>;
        fn ssl_ciphers(self: &PortConfig) -> Box<OptionalString>;
        fn permessage_deflate(self: &PortConfig) -> Box<OptionalBool>;
        fn client_max_window_bits(self: &PortConfig) -> Box<OptionalU8>;
        fn server_max_window_bits(self: &PortConfig) -> Box<OptionalU8>;
        fn client_no_context_takeover(self: &PortConfig) -> Box<OptionalBool>;
        fn server_no_context_takeover(self: &PortConfig) -> Box<OptionalBool>;
        fn compress_level(self: &PortConfig) -> Box<OptionalU8>;
        fn memory_level(self: &PortConfig) -> Box<OptionalU8>;

        // ----- PortConfig: phase-2 hand-written -----
        fn protocols(self: &PortConfig) -> Vec<Protocol>;
        fn limit(self: &PortConfig) -> Box<OptionalPortLimit>;

        // ----- Grpc -----
        fn ip(self: &Grpc) -> Box<OptionalString>;
        fn port(self: &Grpc) -> Box<OptionalU32>;
        fn secure_gateway(self: &Grpc) -> &[String];
        fn ssl_cert(self: &Grpc) -> Box<OptionalString>;
        fn ssl_key(self: &Grpc) -> Box<OptionalString>;
        fn ssl_cert_chain(self: &Grpc) -> Box<OptionalString>;
        fn ssl_client_ca(self: &Grpc) -> Box<OptionalString>;

        // ----- Overlay -----
        fn public_ip(self: &Overlay) -> Box<OptionalString>;
        fn ip_limit(self: &Overlay) -> Box<OptionalI32>;
        fn max_unknown_time(self: &Overlay) -> Box<OptionalU32>;
        fn max_diverged_time(self: &Overlay) -> Box<OptionalU32>;

        // ----- ReduceRelay -----
        fn vp_base_squelch_enable(self: &ReduceRelay) -> Box<OptionalBool>;
        fn vp_enable(self: &ReduceRelay) -> Box<OptionalBool>;
        fn vp_base_squelch_max_selected_peers(self: &ReduceRelay) -> Box<OptionalU32>;
        fn tx_enable(self: &ReduceRelay) -> Box<OptionalBool>;
        fn tx_metrics(self: &ReduceRelay) -> Box<OptionalBool>;
        fn tx_min_peers(self: &ReduceRelay) -> Box<OptionalU32>;
        fn tx_relay_percentage(self: &ReduceRelay) -> Box<OptionalU32>;

        // ----- TransactionQueue -----
        fn ledgers_in_queue(self: &TransactionQueue) -> Box<OptionalU32>;
        fn minimum_queue_size(self: &TransactionQueue) -> Box<OptionalU32>;
        fn retry_sequence_percent(self: &TransactionQueue) -> Box<OptionalU32>;
        fn minimum_escalation_multiplier(self: &TransactionQueue) -> Box<OptionalU32>;
        fn minimum_txn_in_ledger(self: &TransactionQueue) -> Box<OptionalU32>;
        fn minimum_txn_in_ledger_standalone(self: &TransactionQueue) -> Box<OptionalU32>;
        fn target_txn_in_ledger(self: &TransactionQueue) -> Box<OptionalU32>;
        fn maximum_txn_in_ledger(self: &TransactionQueue) -> Box<OptionalU32>;
        fn normal_consensus_increase_percent(self: &TransactionQueue) -> Box<OptionalU32>;
        fn slow_consensus_decrease_percent(self: &TransactionQueue) -> Box<OptionalU32>;
        fn maximum_txn_per_account(self: &TransactionQueue) -> Box<OptionalU32>;
        fn minimum_last_ledger_buffer(self: &TransactionQueue) -> Box<OptionalU32>;
        fn zero_basefee_transaction_feelevel(self: &TransactionQueue) -> Box<OptionalU64>;

        // ----- HashRouter -----
        fn hold_time(self: &HashRouter) -> Box<OptionalI32>;
        fn relay_time(self: &HashRouter) -> Box<OptionalI32>;

        // ----- Sqlite -----
        fn page_size(self: &Sqlite) -> Box<OptionalU32>;
        fn journal_size_limit(self: &Sqlite) -> Box<OptionalU64>;
        fn safety_level(self: &Sqlite) -> Box<OptionalSafetyLevel>;
        fn journal_mode(self: &Sqlite) -> Box<OptionalJournalMode>;
        fn synchronous(self: &Sqlite) -> Box<OptionalSynchronous>;
        fn temp_store(self: &Sqlite) -> Box<OptionalTempStore>;

        // ----- Sqdb -----
        fn backend(self: &Sqdb) -> Box<OptionalSqdbBackend>;

        // ----- LedgerTxTables -----
        fn use_tx_tables(self: &LedgerTxTables) -> Box<OptionalBool>;

        // ----- Insight -----
        fn address(self: &Insight) -> Box<OptionalString>;
        fn prefix(self: &Insight) -> Box<OptionalString>;
        fn server(self: &Insight) -> Box<OptionalInsightServer>;

        // ----- Perf -----
        fn perf_log(self: &Perf) -> Box<OptionalString>;
        fn log_interval(self: &Perf) -> Box<OptionalU64>;

        // ----- Voting -----
        fn reference_fee(self: &Voting) -> Box<OptionalU64>;
        fn account_reserve(self: &Voting) -> Box<OptionalU32>;
        fn owner_reserve(self: &Voting) -> Box<OptionalU32>;

        // ----- Crawl -----
        fn enabled(self: &Crawl) -> Box<OptionalBool>;
        fn overlay(self: &Crawl) -> Box<OptionalBool>;
        fn server(self: &Crawl) -> Box<OptionalBool>;
        fn counts(self: &Crawl) -> Box<OptionalBool>;
        fn unl(self: &Crawl) -> Box<OptionalBool>;

        // ----- Vl -----
        fn enabled(self: &Vl) -> Box<OptionalBool>;
    }
}

pub use bridge::*;

// ---- Schema -> ffi enum conversions ----
//
// The schema enums live in `crate::schema::*` and carry serde plumbing; the
// cxx-shared enums live in `crate::ffi::*` (re-exported from the bridge
// above) and are the wire types crossing the FFI boundary. These `From`
// impls bridge the two coordinate systems.

impl From<SchemaRelayMode> for RelayMode {
    fn from(v: SchemaRelayMode) -> Self {
        match v {
            SchemaRelayMode::All => RelayMode::All,
            SchemaRelayMode::Trusted => RelayMode::Trusted,
            SchemaRelayMode::DropUntrusted => RelayMode::DropUntrusted,
        }
    }
}

impl From<SchemaSafetyLevel> for SafetyLevel {
    fn from(v: SchemaSafetyLevel) -> Self {
        match v {
            SchemaSafetyLevel::High => SafetyLevel::High,
            SchemaSafetyLevel::Low => SafetyLevel::Low,
        }
    }
}

impl From<SchemaJournalMode> for JournalMode {
    fn from(v: SchemaJournalMode) -> Self {
        match v {
            SchemaJournalMode::Delete => JournalMode::Delete,
            SchemaJournalMode::Truncate => JournalMode::Truncate,
            SchemaJournalMode::Persist => JournalMode::Persist,
            SchemaJournalMode::Memory => JournalMode::Memory,
            SchemaJournalMode::Wal => JournalMode::Wal,
            SchemaJournalMode::Off => JournalMode::Off,
        }
    }
}

impl From<SchemaSynchronous> for Synchronous {
    fn from(v: SchemaSynchronous) -> Self {
        match v {
            SchemaSynchronous::Off => Synchronous::Off,
            SchemaSynchronous::Normal => Synchronous::Normal,
            SchemaSynchronous::Full => Synchronous::Full,
            SchemaSynchronous::Extra => Synchronous::Extra,
        }
    }
}

impl From<SchemaTempStore> for TempStore {
    fn from(v: SchemaTempStore) -> Self {
        match v {
            SchemaTempStore::Default => TempStore::Default,
            SchemaTempStore::File => TempStore::File,
            SchemaTempStore::Memory => TempStore::Memory,
        }
    }
}

impl From<SchemaSqdbBackend> for SqdbBackend {
    fn from(v: SchemaSqdbBackend) -> Self {
        match v {
            SchemaSqdbBackend::Sqlite => SqdbBackend::Sqlite,
        }
    }
}

impl From<SchemaInsightServer> for InsightServer {
    fn from(v: SchemaInsightServer) -> Self {
        match v {
            SchemaInsightServer::Statsd => InsightServer::Statsd,
        }
    }
}

impl From<SchemaProtocol> for Protocol {
    fn from(v: SchemaProtocol) -> Self {
        match v {
            SchemaProtocol::Http => Protocol::Http,
            SchemaProtocol::Https => Protocol::Https,
            SchemaProtocol::Ws => Protocol::Ws,
            SchemaProtocol::Wss => Protocol::Wss,
            SchemaProtocol::Peer => Protocol::Peer,
        }
    }
}

// ---- Bridge thunk implementations ----
//
// cxx routes the bridge's `parse_*` declarations to free functions defined
// here. The actual logic lives in `crate::parse_from_toml_str` etc.; these
// thunks adapt the signatures (cxx wants bare `&str` paths and a `Box<...>`
// return for opaque types) and lift the parser `Result` into a `ParseOutcome`.

fn parse_from_toml_str(s: &str) -> Box<ParseOutcome> {
    ParseOutcome::from_result(crate::parse_from_toml_str(s))
}

fn parse_from_ini_str(s: &str) -> Box<ParseOutcome> {
    ParseOutcome::from_result(crate::parse_from_ini_str(s))
}

fn parse_from_file(path: &str) -> Box<ParseOutcome> {
    ParseOutcome::from_result(crate::parse_from_file(path))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ok_outcome(s: &str) -> Box<Config> {
        let mut outcome = super::parse_from_toml_str(s);
        assert!(
            outcome.has_value(),
            "parse failed: {}",
            outcome.error().unwrap_or_default()
        );
        outcome.value().expect("has_value=true")
    }

    #[test]
    fn parse_outcome_carries_value() {
        let outcome = super::parse_from_toml_str("network_quorum = 3");
        assert!(outcome.has_value());
        assert!(!outcome.has_error());
    }

    #[test]
    fn parse_outcome_carries_error() {
        let outcome = super::parse_from_toml_str("not_a_real_key = 1");
        assert!(!outcome.has_value());
        assert!(outcome.has_error());
        let msg = outcome.error().expect("has_error=true");
        assert!(msg.contains("not_a_real_key"), "{msg}");
    }

    #[test]
    fn parse_outcome_value_throws_on_error_arm() {
        let mut outcome = super::parse_from_toml_str("not_a_real_key = 1");
        assert!(outcome.value().is_err());
    }

    #[test]
    fn parse_outcome_error_throws_on_value_arm() {
        let outcome = super::parse_from_toml_str("network_quorum = 3");
        assert!(outcome.error().is_err());
    }

    #[test]
    fn parse_outcome_value_consumed_once() {
        let mut outcome = super::parse_from_toml_str("network_quorum = 3");
        assert!(outcome.value().is_ok());
        assert!(outcome.value().is_err());
    }

    #[test]
    fn scalar_getter_present() {
        let cfg = ok_outcome("network_quorum = 3");
        let q = cfg.network_quorum();
        assert!(q.has_value());
        assert_eq!(q.value().unwrap(), 3);
    }

    #[test]
    fn scalar_getter_absent_throws_on_value() {
        let cfg = ok_outcome("");
        let q = cfg.network_quorum();
        assert!(!q.has_value());
        assert!(q.value().is_err());
    }

    #[test]
    fn scalar_value_or_supplies_fallback() {
        let cfg = ok_outcome("");
        assert_eq!(cfg.network_quorum().value_or(42), 42);
        let cfg = ok_outcome("network_quorum = 7");
        assert_eq!(cfg.network_quorum().value_or(42), 7);
    }

    #[test]
    fn string_getter_handles_pathbuf() {
        let cfg = ok_outcome(r#"debug_logfile = "/var/log/xrpld.log""#);
        let p = cfg.debug_logfile();
        assert!(p.has_value());
        assert_eq!(p.value().unwrap(), "/var/log/xrpld.log");
    }

    #[test]
    fn vec_string_getter_returns_slice() {
        let cfg = ok_outcome(r#"ips = ["r.ripple.com 51235", "s2.ripple.com 51235"]"#);
        assert_eq!(cfg.ips(), &["r.ripple.com 51235", "s2.ripple.com 51235"]);
    }

    #[test]
    fn has_x_companion_reports_presence() {
        let cfg = ok_outcome(
            r#"
                [overlay]
                ip_limit = 50
            "#,
        );
        assert!(cfg.has_overlay());
        assert!(!cfg.has_grpc());
    }

    #[test]
    fn nested_getter_ok_when_present() {
        let cfg = ok_outcome(
            r#"
                [overlay]
                ip_limit = 50
            "#,
        );
        let overlay = cfg.overlay().expect("overlay set");
        assert_eq!(overlay.ip_limit().value().unwrap(), 50);
    }

    #[test]
    fn nested_getter_err_when_absent() {
        let cfg = ok_outcome("");
        let err = cfg.overlay().unwrap_err();
        assert!(err.contains("overlay"), "{err}");
    }

    #[test]
    fn server_defaults_flatten_visible_via_getter() {
        let cfg = ok_outcome(
            r#"
                [server]
                send_queue_limit = 500

                [server.ports.port_peer]
                ip = "0.0.0.0"
                port = 51235
            "#,
        );
        let srv = cfg.server().expect("server set");
        let defaults = srv.defaults();
        assert!(defaults.send_queue_limit().has_value());
        assert_eq!(defaults.send_queue_limit().value().unwrap(), 500);
    }

    #[test]
    fn option_vec_string_returns_empty_slice_when_absent() {
        let cfg = ok_outcome(
            r#"
                [server]
                send_queue_limit = 500
            "#,
        );
        let srv = cfg.server().unwrap();
        assert!(srv.defaults().admin().is_empty());
    }

    // ===== Phase-2 tests =====
    //
    // cxx-shared enums do not auto-derive `Debug`, so `assert_eq!` on the
    // raw enum value won't compile. We use `matches!` (boolean pattern
    // match) or cast via discriminant for value checks throughout.

    // ----- Data-less optional-enum wrappers -----

    #[test]
    fn relay_proposals_present_returns_variant() {
        let cfg = ok_outcome(r#"relay_proposals = "trusted""#);
        let v = cfg.relay_proposals();
        assert!(v.has_value());
        assert!(matches!(v.value().unwrap(), RelayMode::Trusted));
    }

    #[test]
    fn relay_proposals_absent_value_throws() {
        let cfg = ok_outcome("");
        let v = cfg.relay_proposals();
        assert!(!v.has_value());
        assert!(v.value().is_err());
        // value_or returns the fallback when absent.
        assert!(matches!(v.value_or(RelayMode::All), RelayMode::All));
    }

    #[test]
    fn relay_validations_uses_same_optional_relay_mode() {
        let cfg = ok_outcome(r#"relay_validations = "drop_untrusted""#);
        assert!(matches!(
            cfg.relay_validations().value().unwrap(),
            RelayMode::DropUntrusted
        ));
    }

    #[test]
    fn sqlite_safety_level_present() {
        let cfg = ok_outcome(
            r#"
                [sqlite]
                safety_level = "high"
            "#,
        );
        let s = cfg.sqlite().unwrap();
        assert!(s.safety_level().has_value());
        assert!(matches!(
            s.safety_level().value().unwrap(),
            SafetyLevel::High
        ));
    }

    #[test]
    fn sqlite_safety_level_absent() {
        let cfg = ok_outcome(
            r#"
                [sqlite]
                page_size = 4096
            "#,
        );
        let s = cfg.sqlite().unwrap();
        assert!(!s.safety_level().has_value());
        assert!(s.safety_level().value().is_err());
    }

    #[test]
    fn sqlite_journal_mode_all_variants_roundtrip() {
        // Each variant is matched explicitly to avoid the missing-Debug
        // problem with cxx-shared enums.
        fn check(name: &str, p: impl Fn(JournalMode) -> bool) {
            let cfg = ok_outcome(&format!(
                r#"
                    [sqlite]
                    journal_mode = "{name}"
                "#
            ));
            let s = cfg.sqlite().unwrap();
            assert!(p(s.journal_mode().value().unwrap()), "{name}");
        }
        check("delete", |v| matches!(v, JournalMode::Delete));
        check("truncate", |v| matches!(v, JournalMode::Truncate));
        check("persist", |v| matches!(v, JournalMode::Persist));
        check("memory", |v| matches!(v, JournalMode::Memory));
        check("wal", |v| matches!(v, JournalMode::Wal));
        check("off", |v| matches!(v, JournalMode::Off));
    }

    #[test]
    fn sqlite_synchronous_present() {
        let cfg = ok_outcome(
            r#"
                [sqlite]
                synchronous = "extra"
            "#,
        );
        assert!(matches!(
            cfg.sqlite().unwrap().synchronous().value().unwrap(),
            Synchronous::Extra
        ));
    }

    #[test]
    fn sqlite_temp_store_present_and_absent() {
        let cfg = ok_outcome(
            r#"
                [sqlite]
                temp_store = "memory"
            "#,
        );
        assert!(matches!(
            cfg.sqlite().unwrap().temp_store().value().unwrap(),
            TempStore::Memory
        ));

        let cfg = ok_outcome(
            r#"
                [sqlite]
                page_size = 4096
            "#,
        );
        assert!(!cfg.sqlite().unwrap().temp_store().has_value());
    }

    #[test]
    fn sqdb_backend_present_and_absent() {
        let cfg = ok_outcome(
            r#"
                [sqdb]
                backend = "sqlite"
            "#,
        );
        assert!(matches!(
            cfg.sqdb().unwrap().backend().value().unwrap(),
            SqdbBackend::Sqlite
        ));

        let cfg = ok_outcome("[sqdb]");
        assert!(!cfg.sqdb().unwrap().backend().has_value());
    }

    #[test]
    fn insight_server_present_and_absent() {
        let cfg = ok_outcome(
            r#"
                [insight]
                server = "statsd"
            "#,
        );
        assert!(matches!(
            cfg.insight().unwrap().server().value().unwrap(),
            InsightServer::Statsd
        ));

        let cfg = ok_outcome(
            r#"
                [insight]
                prefix = "x"
            "#,
        );
        assert!(!cfg.insight().unwrap().server().has_value());
    }

    // ----- Polymorphic wrappers -----

    #[test]
    fn ledger_history_named_full() {
        let cfg = ok_outcome(r#"ledger_history = "full""#);
        let h = cfg.ledger_history();
        assert!(h.has_value());
        assert!(matches!(h.kind().unwrap(), LedgerHistoryKind::Full));
        // numeric_value throws because the kind is not Numeric.
        assert!(h.numeric_value().is_err());
    }

    #[test]
    fn ledger_history_named_none() {
        let cfg = ok_outcome(r#"ledger_history = "none""#);
        assert!(matches!(
            cfg.ledger_history().kind().unwrap(),
            LedgerHistoryKind::None
        ));
    }

    #[test]
    fn ledger_history_numeric() {
        let cfg = ok_outcome("ledger_history = 100000");
        let h = cfg.ledger_history();
        assert!(matches!(h.kind().unwrap(), LedgerHistoryKind::Numeric));
        assert_eq!(h.numeric_value().unwrap(), 100_000);
    }

    #[test]
    fn ledger_history_absent_throws_on_kind() {
        let cfg = ok_outcome("");
        let h = cfg.ledger_history();
        assert!(!h.has_value());
        assert!(h.kind().is_err());
        assert!(h.numeric_value().is_err());
    }

    #[test]
    fn fetch_depth_named_and_numeric() {
        let cfg = ok_outcome(r#"fetch_depth = "full""#);
        assert!(matches!(
            cfg.fetch_depth().kind().unwrap(),
            FetchDepthKind::Full
        ));

        let cfg = ok_outcome("fetch_depth = 5000");
        let fd = cfg.fetch_depth();
        assert!(matches!(fd.kind().unwrap(), FetchDepthKind::Numeric));
        assert_eq!(fd.numeric_value().unwrap(), 5000);
    }

    #[test]
    fn network_id_named_main() {
        let cfg = ok_outcome(r#"network_id = "main""#);
        assert!(matches!(
            cfg.network_id().kind().unwrap(),
            NetworkIdKind::Main
        ));
        assert!(cfg.network_id().numeric_value().is_err());
    }

    #[test]
    fn network_id_named_testnet() {
        let cfg = ok_outcome(r#"network_id = "testnet""#);
        assert!(matches!(
            cfg.network_id().kind().unwrap(),
            NetworkIdKind::Testnet
        ));
    }

    #[test]
    fn network_id_named_devnet() {
        let cfg = ok_outcome(r#"network_id = "devnet""#);
        assert!(matches!(
            cfg.network_id().kind().unwrap(),
            NetworkIdKind::Devnet
        ));
    }

    #[test]
    fn network_id_numeric() {
        let cfg = ok_outcome("network_id = 1234");
        let n = cfg.network_id();
        assert!(matches!(n.kind().unwrap(), NetworkIdKind::Numeric));
        assert_eq!(n.numeric_value().unwrap(), 1234);
    }

    #[test]
    fn node_size_named_huge() {
        let cfg = ok_outcome(r#"node_size = "huge""#);
        let n = cfg.node_size();
        assert!(matches!(n.kind().unwrap(), NodeSizeKind::Huge));
        assert!(n.numeric_value().is_err());
    }

    #[test]
    fn node_size_numeric() {
        let cfg = ok_outcome("node_size = 3");
        let n = cfg.node_size();
        assert!(matches!(n.kind().unwrap(), NodeSizeKind::Numeric));
        assert_eq!(n.numeric_value().unwrap(), 3u8);
    }

    #[test]
    fn node_size_absent() {
        let cfg = ok_outcome("");
        let n = cfg.node_size();
        assert!(!n.has_value());
        assert!(n.kind().is_err());
    }

    // ----- NodeDb tagged wrapper -----

    #[test]
    fn node_db_absent() {
        let cfg = ok_outcome("");
        let db = cfg.node_db();
        assert!(!db.has_value());
        assert!(db.kind().is_err());
        assert!(db.path().is_err());
        // Variant-specific fields are absent when has_value() is false.
        assert!(!db.nudb_block_size().has_value());
        assert!(!db.cache_mb().has_value());
        assert!(!db.filter_bits().has_value());
    }

    #[test]
    fn node_db_nudb_variant() {
        let cfg = ok_outcome(
            r#"
                [node_db]
                type            = "NuDB"
                path            = "/var/lib/xrpld/nudb"
                online_delete   = 2000
                nudb_block_size = 4096
            "#,
        );
        let db = cfg.node_db();
        assert!(db.has_value());
        assert!(matches!(db.kind().unwrap(), NodeDbKind::NuDb));
        assert_eq!(db.path().unwrap(), "/var/lib/xrpld/nudb");
        assert!(db.online_delete().has_value());
        assert_eq!(db.online_delete().value().unwrap(), 2000);
        assert!(db.nudb_block_size().has_value());
        assert_eq!(db.nudb_block_size().value().unwrap(), 4096);
        // RocksDB-only fields are silently absent — no throw.
        assert!(!db.cache_mb().has_value());
        assert!(!db.filter_bits().has_value());
    }

    #[test]
    fn node_db_rocksdb_variant() {
        let cfg = ok_outcome(
            r#"
                [node_db]
                type     = "RocksDB"
                path     = "/var/lib/xrpld/rocksdb"
                cache_mb = 512
            "#,
        );
        let db = cfg.node_db();
        assert!(matches!(db.kind().unwrap(), NodeDbKind::RocksDb));
        assert_eq!(db.path().unwrap(), "/var/lib/xrpld/rocksdb");
        assert!(db.cache_mb().has_value());
        assert_eq!(db.cache_mb().value().unwrap(), 512);
        // NuDB-only field is silently absent.
        assert!(!db.nudb_block_size().has_value());
    }

    #[test]
    fn node_db_common_fields_visible_on_either_variant() {
        let cfg = ok_outcome(
            r#"
                [node_db]
                type                 = "RocksDB"
                path                 = "/p"
                fast_load            = true
                earliest_seq         = 32570
                online_delete        = 2000
                advisory_delete      = true
                delete_batch         = 100
                back_off_milliseconds = 200
                age_threshold_seconds = 60
                recovery_wait_seconds = 5
            "#,
        );
        let db = cfg.node_db();
        assert_eq!(db.fast_load().value().unwrap(), true);
        assert_eq!(db.earliest_seq().value().unwrap(), 32570);
        assert_eq!(db.online_delete().value().unwrap(), 2000);
        assert_eq!(db.advisory_delete().value().unwrap(), true);
        assert_eq!(db.delete_batch().value().unwrap(), 100);
        assert_eq!(db.back_off_milliseconds().value().unwrap(), 200);
        assert_eq!(db.age_threshold_seconds().value().unwrap(), 60);
        assert_eq!(db.recovery_wait_seconds().value().unwrap(), 5);
    }

    #[test]
    fn import_db_uses_same_wrapper() {
        let cfg = ok_outcome(
            r#"
                [import_db]
                type = "NuDB"
                path = "/import"
            "#,
        );
        let db = cfg.import_db();
        assert!(matches!(db.kind().unwrap(), NodeDbKind::NuDb));
        assert_eq!(db.path().unwrap(), "/import");
        assert!(!cfg.node_db().has_value());
    }

    // ----- Server::ports map -----

    #[test]
    fn server_port_names_sorted_and_lookup_round_trip() {
        let cfg = ok_outcome(
            r#"
                [server]
                send_queue_limit = 500

                [server.ports.port_rpc]
                ip       = "127.0.0.1"
                port     = 5005
                protocol = ["http", "https"]
                limit    = 200

                [server.ports.port_peer]
                ip       = "0.0.0.0"
                port     = 51235
                protocol = ["peer"]
                limit    = "unlimited"
            "#,
        );
        let srv = cfg.server().unwrap();
        let names = srv.port_names();
        // BTreeMap iteration order is lexicographic.
        assert_eq!(names, vec!["port_peer".to_string(), "port_rpc".to_string()]);
        assert!(srv.has_port("port_peer"));
        assert!(srv.has_port("port_rpc"));
        assert!(!srv.has_port("nope"));

        let peer = srv.port("port_peer").unwrap();
        assert_eq!(peer.port().value().unwrap(), 51235);
        let rpc = srv.port("port_rpc").unwrap();
        assert_eq!(rpc.port().value().unwrap(), 5005);
    }

    #[test]
    fn server_port_missing_throws() {
        let cfg = ok_outcome(
            r#"
                [server]
                send_queue_limit = 500
            "#,
        );
        let srv = cfg.server().unwrap();
        assert!(srv.port_names().is_empty());
        let err = srv.port("missing").unwrap_err();
        assert!(err.contains("missing"), "{err}");
    }

    // ----- PortConfig protocols + limit -----

    #[test]
    fn port_protocols_returned_in_order() {
        let cfg = ok_outcome(
            r#"
                [server.ports.port_rpc]
                ip       = "127.0.0.1"
                port     = 5005
                protocol = ["http", "https", "ws"]
            "#,
        );
        let rpc = cfg.server().unwrap().port("port_rpc").unwrap();
        let ps = rpc.protocols();
        assert_eq!(ps.len(), 3);
        assert!(matches!(ps[0], Protocol::Http));
        assert!(matches!(ps[1], Protocol::Https));
        assert!(matches!(ps[2], Protocol::Ws));
    }

    #[test]
    fn port_protocols_empty_when_absent() {
        let cfg = ok_outcome(
            r#"
                [server.ports.port_rpc]
                ip   = "127.0.0.1"
                port = 5005
            "#,
        );
        let rpc = cfg.server().unwrap().port("port_rpc").unwrap();
        assert!(rpc.protocols().is_empty());
    }

    #[test]
    fn port_limit_unlimited_kind() {
        let cfg = ok_outcome(
            r#"
                [server.ports.port_peer]
                ip    = "0.0.0.0"
                port  = 51235
                limit = "unlimited"
            "#,
        );
        let peer = cfg.server().unwrap().port("port_peer").unwrap();
        let lim = peer.limit();
        assert!(lim.has_value());
        assert!(matches!(lim.kind().unwrap(), PortLimitKind::Unlimited));
        // Numeric accessor throws when the kind isn't Numeric.
        assert!(lim.numeric_value().is_err());
    }

    #[test]
    fn port_limit_numeric_kind() {
        let cfg = ok_outcome(
            r#"
                [server.ports.port_rpc]
                ip    = "127.0.0.1"
                port  = 5005
                limit = 200
            "#,
        );
        let rpc = cfg.server().unwrap().port("port_rpc").unwrap();
        let lim = rpc.limit();
        assert!(matches!(lim.kind().unwrap(), PortLimitKind::Numeric));
        assert_eq!(lim.numeric_value().unwrap(), 200u16);
    }

    #[test]
    fn port_limit_absent() {
        let cfg = ok_outcome(
            r#"
                [server.ports.port_rpc]
                ip   = "127.0.0.1"
                port = 5005
            "#,
        );
        let rpc = cfg.server().unwrap().port("port_rpc").unwrap();
        let lim = rpc.limit();
        assert!(!lim.has_value());
        assert!(lim.kind().is_err());
        assert!(lim.numeric_value().is_err());
    }
}
