//! Guest side of the host/guest ABI.
//!
//! There is nothing hand-written here anymore: the guest bindings — the
//! `wasm_import_module = "host"` import block and the `GuestHost`
//! implementation of [`HostFunctions`] — are generated by the `host_abi!`
//! macro alongside the trait itself, and live (wasm32-gated) in the
//! `host_functions` crate. This crate just re-exports them, so a contract
//! author depends on `stdlib` and gets both the trait and its guest
//! implementation from one place, with no duplicated ABI to drift.
#![no_std]

pub use host_functions::{HASH_LEN, HostError, HostFunctions, HostResult};

/// The production guest host: every [`HostFunctions`] method forwards to a wasm
/// import. Only exists for the wasm32 guest target.
#[cfg(target_arch = "wasm32")]
pub use host_functions::GuestHost;
